// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module keccak_top_keccak_top_Pipeline_SQUEEZE_BLOCK (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_stream_TREADY,
        output_remaining,
        trunc_ln6,
        state_load_2,
        state_1_load_2,
        state_2_load_2,
        state_3_load_2,
        state_4_load_2,
        state_5_load_2,
        state_6_load_2,
        state_7_load_2,
        state_8_load_2,
        state_9_load_2,
        state_10_load_2,
        state_11_load_2,
        state_12_load_2,
        state_13_load_2,
        state_14_load_2,
        state_15_load_2,
        state_16_load_2,
        state_17_load_2,
        state_18_load_2,
        state_19_load_2,
        state_20_load_2,
        state_21_load_2,
        state_22_load_2,
        state_23_load_2,
        state_24_load_2,
        output_stream_TDATA,
        output_stream_TVALID,
        output_stream_TKEEP,
        output_stream_TSTRB,
        output_stream_TLAST,
        output_remaining_1_out,
        output_remaining_1_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   output_stream_TREADY;
input  [30:0] output_remaining;
input  [5:0] trunc_ln6;
input  [63:0] state_load_2;
input  [63:0] state_1_load_2;
input  [63:0] state_2_load_2;
input  [63:0] state_3_load_2;
input  [63:0] state_4_load_2;
input  [63:0] state_5_load_2;
input  [63:0] state_6_load_2;
input  [63:0] state_7_load_2;
input  [63:0] state_8_load_2;
input  [63:0] state_9_load_2;
input  [63:0] state_10_load_2;
input  [63:0] state_11_load_2;
input  [63:0] state_12_load_2;
input  [63:0] state_13_load_2;
input  [63:0] state_14_load_2;
input  [63:0] state_15_load_2;
input  [63:0] state_16_load_2;
input  [63:0] state_17_load_2;
input  [63:0] state_18_load_2;
input  [63:0] state_19_load_2;
input  [63:0] state_20_load_2;
input  [63:0] state_21_load_2;
input  [63:0] state_22_load_2;
input  [63:0] state_23_load_2;
input  [63:0] state_24_load_2;
output  [63:0] output_stream_TDATA;
output   output_stream_TVALID;
output  [7:0] output_stream_TKEEP;
output  [7:0] output_stream_TSTRB;
output  [0:0] output_stream_TLAST;
output  [31:0] output_remaining_1_out;
output   output_remaining_1_out_ap_vld;

reg ap_idle;
reg output_stream_TVALID;
reg output_remaining_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln348_fu_386_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    output_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] p_0_fu_404_p53;
reg   [63:0] p_0_reg_709;
wire   [0:0] icmp_ln353_fu_497_p2;
reg   [0:0] icmp_ln353_reg_714;
wire   [31:0] output_remaining_2_fu_511_p2;
reg   [31:0] output_remaining_2_reg_719;
wire   [7:0] trunc_ln357_fu_523_p1;
reg   [7:0] trunc_ln357_reg_724;
reg   [31:0] output_remaining_1_fu_176;
wire   [31:0] output_remaining_cast_fu_369_p1;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [5:0] i_fu_180;
wire   [5:0] add_ln348_fu_391_p2;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [7:0] select_ln357_fu_548_p3;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_01001;
wire   [63:0] p_0_fu_404_p51;
wire   [4:0] p_0_fu_404_p52;
wire   [28:0] tmp_fu_487_p4;
wire   [31:0] bytes_out_fu_503_p3;
wire   [31:0] shl_ln357_fu_517_p2;
wire   [7:0] add_ln357_fu_543_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [4:0] p_0_fu_404_p1;
wire   [4:0] p_0_fu_404_p3;
wire   [4:0] p_0_fu_404_p5;
wire   [4:0] p_0_fu_404_p7;
wire   [4:0] p_0_fu_404_p9;
wire   [4:0] p_0_fu_404_p11;
wire   [4:0] p_0_fu_404_p13;
wire   [4:0] p_0_fu_404_p15;
wire   [4:0] p_0_fu_404_p17;
wire   [4:0] p_0_fu_404_p19;
wire   [4:0] p_0_fu_404_p21;
wire   [4:0] p_0_fu_404_p23;
wire   [4:0] p_0_fu_404_p25;
wire   [4:0] p_0_fu_404_p27;
wire   [4:0] p_0_fu_404_p29;
wire   [4:0] p_0_fu_404_p31;
wire  signed [4:0] p_0_fu_404_p33;
wire  signed [4:0] p_0_fu_404_p35;
wire  signed [4:0] p_0_fu_404_p37;
wire  signed [4:0] p_0_fu_404_p39;
wire  signed [4:0] p_0_fu_404_p41;
wire  signed [4:0] p_0_fu_404_p43;
wire  signed [4:0] p_0_fu_404_p45;
wire  signed [4:0] p_0_fu_404_p47;
wire  signed [4:0] p_0_fu_404_p49;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 output_remaining_1_fu_176 = 32'd0;
#0 i_fu_180 = 6'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) keccak_top_sparsemux_51_5_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 64 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 64 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 64 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 64 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 64 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 64 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 64 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 64 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 64 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 64 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 64 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 64 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 64 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 64 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 64 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 64 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 64 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 64 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 64 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 64 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 64 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 64 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 64 ))
sparsemux_51_5_64_1_1_U61(
    .din0(state_load_2),
    .din1(state_1_load_2),
    .din2(state_2_load_2),
    .din3(state_3_load_2),
    .din4(state_4_load_2),
    .din5(state_5_load_2),
    .din6(state_6_load_2),
    .din7(state_7_load_2),
    .din8(state_8_load_2),
    .din9(state_9_load_2),
    .din10(state_10_load_2),
    .din11(state_11_load_2),
    .din12(state_12_load_2),
    .din13(state_13_load_2),
    .din14(state_14_load_2),
    .din15(state_15_load_2),
    .din16(state_16_load_2),
    .din17(state_17_load_2),
    .din18(state_18_load_2),
    .din19(state_19_load_2),
    .din20(state_20_load_2),
    .din21(state_21_load_2),
    .din22(state_22_load_2),
    .din23(state_23_load_2),
    .din24(state_24_load_2),
    .def(p_0_fu_404_p51),
    .sel(p_0_fu_404_p52),
    .dout(p_0_fu_404_p53)
);

keccak_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_180 <= 6'd0;
        end else if (((icmp_ln348_fu_386_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_180 <= add_ln348_fu_391_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            output_remaining_1_fu_176 <= output_remaining_cast_fu_369_p1;
        end else if (((icmp_ln348_fu_386_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            output_remaining_1_fu_176 <= output_remaining_2_fu_511_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln353_reg_714 <= icmp_ln353_fu_497_p2;
        output_remaining_2_reg_719 <= output_remaining_2_fu_511_p2;
        p_0_reg_709 <= p_0_fu_404_p53;
        trunc_ln357_reg_724 <= trunc_ln357_fu_523_p1;
    end
end

always @ (*) begin
    if (((icmp_ln348_fu_386_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln348_fu_386_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_remaining_1_out_ap_vld = 1'b1;
    end else begin
        output_remaining_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output_stream_TDATA_blk_n = output_stream_TREADY;
    end else begin
        output_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output_stream_TVALID = 1'b1;
    end else begin
        output_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln348_fu_391_p2 = (i_fu_180 + 6'd1);

assign add_ln357_fu_543_p2 = ($signed(trunc_ln357_reg_724) + $signed(8'd255));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((output_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((output_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((output_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((output_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((output_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign bytes_out_fu_503_p3 = ((icmp_ln353_fu_497_p2[0:0] == 1'b1) ? 32'd8 : output_remaining_1_fu_176);

assign icmp_ln348_fu_386_p2 = ((i_fu_180 == trunc_ln6) ? 1'b1 : 1'b0);

assign icmp_ln353_fu_497_p2 = (($signed(tmp_fu_487_p4) > $signed(29'd0)) ? 1'b1 : 1'b0);

assign output_remaining_1_out = output_remaining_1_fu_176;

assign output_remaining_2_fu_511_p2 = (output_remaining_1_fu_176 - bytes_out_fu_503_p3);

assign output_remaining_cast_fu_369_p1 = output_remaining;

assign output_stream_TDATA = p_0_reg_709;

assign output_stream_TKEEP = select_ln357_fu_548_p3;

assign output_stream_TLAST = (($signed(output_remaining_2_reg_719) < $signed(32'd1)) ? 1'b1 : 1'b0);

assign output_stream_TSTRB = select_ln357_fu_548_p3;

assign p_0_fu_404_p51 = 'bx;

assign p_0_fu_404_p52 = i_fu_180[4:0];

assign select_ln357_fu_548_p3 = ((icmp_ln353_reg_714[0:0] == 1'b1) ? 8'd255 : add_ln357_fu_543_p2);

assign shl_ln357_fu_517_p2 = 32'd1 << bytes_out_fu_503_p3;

assign tmp_fu_487_p4 = {{output_remaining_1_fu_176[31:3]}};

assign trunc_ln357_fu_523_p1 = shl_ln357_fu_517_p2[7:0];

endmodule //keccak_top_keccak_top_Pipeline_SQUEEZE_BLOCK
