// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module keccak_top_keccak_top_Pipeline_ABSORB_BLOCK (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_stream_TVALID,
        message_done,
        trunc_ln1,
        state_24_i,
        state_24_o,
        state_24_o_ap_vld,
        state_23_i,
        state_23_o,
        state_23_o_ap_vld,
        state_22_i,
        state_22_o,
        state_22_o_ap_vld,
        state_21_i,
        state_21_o,
        state_21_o_ap_vld,
        state_20_i,
        state_20_o,
        state_20_o_ap_vld,
        state_19_i,
        state_19_o,
        state_19_o_ap_vld,
        state_18_i,
        state_18_o,
        state_18_o_ap_vld,
        state_17_i,
        state_17_o,
        state_17_o_ap_vld,
        state_16_i,
        state_16_o,
        state_16_o_ap_vld,
        state_15_i,
        state_15_o,
        state_15_o_ap_vld,
        state_14_i,
        state_14_o,
        state_14_o_ap_vld,
        state_13_i,
        state_13_o,
        state_13_o_ap_vld,
        state_12_i,
        state_12_o,
        state_12_o_ap_vld,
        state_11_i,
        state_11_o,
        state_11_o_ap_vld,
        state_10_i,
        state_10_o,
        state_10_o_ap_vld,
        state_9_i,
        state_9_o,
        state_9_o_ap_vld,
        state_8_i,
        state_8_o,
        state_8_o_ap_vld,
        state_7_i,
        state_7_o,
        state_7_o_ap_vld,
        state_6_i,
        state_6_o,
        state_6_o_ap_vld,
        state_5_i,
        state_5_o,
        state_5_o_ap_vld,
        state_4_i,
        state_4_o,
        state_4_o_ap_vld,
        state_3_i,
        state_3_o,
        state_3_o_ap_vld,
        state_2_i,
        state_2_o,
        state_2_o_ap_vld,
        state_1_i,
        state_1_o,
        state_1_o_ap_vld,
        state_i,
        state_o,
        state_o_ap_vld,
        input_stream_TDATA,
        input_stream_TREADY,
        input_stream_TKEEP,
        input_stream_TSTRB,
        input_stream_TLAST,
        message_done_1_out,
        message_done_1_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   input_stream_TVALID;
input  [0:0] message_done;
input  [5:0] trunc_ln1;
input  [63:0] state_24_i;
output  [63:0] state_24_o;
output   state_24_o_ap_vld;
input  [63:0] state_23_i;
output  [63:0] state_23_o;
output   state_23_o_ap_vld;
input  [63:0] state_22_i;
output  [63:0] state_22_o;
output   state_22_o_ap_vld;
input  [63:0] state_21_i;
output  [63:0] state_21_o;
output   state_21_o_ap_vld;
input  [63:0] state_20_i;
output  [63:0] state_20_o;
output   state_20_o_ap_vld;
input  [63:0] state_19_i;
output  [63:0] state_19_o;
output   state_19_o_ap_vld;
input  [63:0] state_18_i;
output  [63:0] state_18_o;
output   state_18_o_ap_vld;
input  [63:0] state_17_i;
output  [63:0] state_17_o;
output   state_17_o_ap_vld;
input  [63:0] state_16_i;
output  [63:0] state_16_o;
output   state_16_o_ap_vld;
input  [63:0] state_15_i;
output  [63:0] state_15_o;
output   state_15_o_ap_vld;
input  [63:0] state_14_i;
output  [63:0] state_14_o;
output   state_14_o_ap_vld;
input  [63:0] state_13_i;
output  [63:0] state_13_o;
output   state_13_o_ap_vld;
input  [63:0] state_12_i;
output  [63:0] state_12_o;
output   state_12_o_ap_vld;
input  [63:0] state_11_i;
output  [63:0] state_11_o;
output   state_11_o_ap_vld;
input  [63:0] state_10_i;
output  [63:0] state_10_o;
output   state_10_o_ap_vld;
input  [63:0] state_9_i;
output  [63:0] state_9_o;
output   state_9_o_ap_vld;
input  [63:0] state_8_i;
output  [63:0] state_8_o;
output   state_8_o_ap_vld;
input  [63:0] state_7_i;
output  [63:0] state_7_o;
output   state_7_o_ap_vld;
input  [63:0] state_6_i;
output  [63:0] state_6_o;
output   state_6_o_ap_vld;
input  [63:0] state_5_i;
output  [63:0] state_5_o;
output   state_5_o_ap_vld;
input  [63:0] state_4_i;
output  [63:0] state_4_o;
output   state_4_o_ap_vld;
input  [63:0] state_3_i;
output  [63:0] state_3_o;
output   state_3_o_ap_vld;
input  [63:0] state_2_i;
output  [63:0] state_2_o;
output   state_2_o_ap_vld;
input  [63:0] state_1_i;
output  [63:0] state_1_o;
output   state_1_o_ap_vld;
input  [63:0] state_i;
output  [63:0] state_o;
output   state_o_ap_vld;
input  [63:0] input_stream_TDATA;
output   input_stream_TREADY;
input  [7:0] input_stream_TKEEP;
input  [7:0] input_stream_TSTRB;
input  [0:0] input_stream_TLAST;
output  [0:0] message_done_1_out;
output   message_done_1_out_ap_vld;

reg ap_idle;
reg[63:0] state_24_o;
reg state_24_o_ap_vld;
reg[63:0] state_23_o;
reg state_23_o_ap_vld;
reg[63:0] state_22_o;
reg state_22_o_ap_vld;
reg[63:0] state_21_o;
reg state_21_o_ap_vld;
reg[63:0] state_20_o;
reg state_20_o_ap_vld;
reg[63:0] state_19_o;
reg state_19_o_ap_vld;
reg[63:0] state_18_o;
reg state_18_o_ap_vld;
reg[63:0] state_17_o;
reg state_17_o_ap_vld;
reg[63:0] state_16_o;
reg state_16_o_ap_vld;
reg[63:0] state_15_o;
reg state_15_o_ap_vld;
reg[63:0] state_14_o;
reg state_14_o_ap_vld;
reg[63:0] state_13_o;
reg state_13_o_ap_vld;
reg[63:0] state_12_o;
reg state_12_o_ap_vld;
reg[63:0] state_11_o;
reg state_11_o_ap_vld;
reg[63:0] state_10_o;
reg state_10_o_ap_vld;
reg[63:0] state_9_o;
reg state_9_o_ap_vld;
reg[63:0] state_8_o;
reg state_8_o_ap_vld;
reg[63:0] state_7_o;
reg state_7_o_ap_vld;
reg[63:0] state_6_o;
reg state_6_o_ap_vld;
reg[63:0] state_5_o;
reg state_5_o_ap_vld;
reg[63:0] state_4_o;
reg state_4_o_ap_vld;
reg[63:0] state_3_o;
reg state_3_o_ap_vld;
reg[63:0] state_2_o;
reg state_2_o_ap_vld;
reg[63:0] state_1_o;
reg state_1_o_ap_vld;
reg[63:0] state_o;
reg state_o_ap_vld;
reg input_stream_TREADY;
reg message_done_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [0:0] tmp_1_nbreadreq_fu_188_p6;
reg    ap_block_state2_pp0_stage0_iter1_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln300_fu_559_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    input_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire   [4:0] trunc_ln300_fu_571_p1;
reg   [4:0] trunc_ln300_reg_815;
reg    ap_block_pp0_stage0_11001;
reg   [5:0] i_fu_168;
wire   [5:0] add_ln300_fu_565_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_i_2;
wire    ap_block_pp0_stage0;
reg   [0:0] message_done_1_fu_172;
wire   [0:0] message_done_2_fu_782_p2;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [63:0] state_25_fu_695_p2;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [63:0] tmp_2_fu_588_p51;
wire   [63:0] tmp_2_fu_588_p53;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [4:0] tmp_2_fu_588_p1;
wire   [4:0] tmp_2_fu_588_p3;
wire   [4:0] tmp_2_fu_588_p5;
wire   [4:0] tmp_2_fu_588_p7;
wire   [4:0] tmp_2_fu_588_p9;
wire   [4:0] tmp_2_fu_588_p11;
wire   [4:0] tmp_2_fu_588_p13;
wire   [4:0] tmp_2_fu_588_p15;
wire   [4:0] tmp_2_fu_588_p17;
wire   [4:0] tmp_2_fu_588_p19;
wire   [4:0] tmp_2_fu_588_p21;
wire   [4:0] tmp_2_fu_588_p23;
wire   [4:0] tmp_2_fu_588_p25;
wire   [4:0] tmp_2_fu_588_p27;
wire   [4:0] tmp_2_fu_588_p29;
wire   [4:0] tmp_2_fu_588_p31;
wire  signed [4:0] tmp_2_fu_588_p33;
wire  signed [4:0] tmp_2_fu_588_p35;
wire  signed [4:0] tmp_2_fu_588_p37;
wire  signed [4:0] tmp_2_fu_588_p39;
wire  signed [4:0] tmp_2_fu_588_p41;
wire  signed [4:0] tmp_2_fu_588_p43;
wire  signed [4:0] tmp_2_fu_588_p45;
wire  signed [4:0] tmp_2_fu_588_p47;
wire  signed [4:0] tmp_2_fu_588_p49;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_fu_168 = 6'd0;
#0 message_done_1_fu_172 = 1'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) keccak_top_sparsemux_51_5_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 64 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 64 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 64 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 64 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 64 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 64 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 64 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 64 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 64 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 64 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 64 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 64 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 64 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 64 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 64 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 64 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 64 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 64 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 64 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 64 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 64 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 64 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 64 ))
sparsemux_51_5_64_1_1_U1(
    .din0(state_i),
    .din1(state_1_i),
    .din2(state_2_i),
    .din3(state_3_i),
    .din4(state_4_i),
    .din5(state_5_i),
    .din6(state_6_i),
    .din7(state_7_i),
    .din8(state_8_i),
    .din9(state_9_i),
    .din10(state_10_i),
    .din11(state_11_i),
    .din12(state_12_i),
    .din13(state_13_i),
    .din14(state_14_i),
    .din15(state_15_i),
    .din16(state_16_i),
    .din17(state_17_i),
    .din18(state_18_i),
    .din19(state_19_i),
    .din20(state_20_i),
    .din21(state_21_i),
    .din22(state_22_i),
    .din23(state_23_i),
    .din24(state_24_i),
    .def(tmp_2_fu_588_p51),
    .sel(trunc_ln300_reg_815),
    .dout(tmp_2_fu_588_p53)
);

keccak_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln300_fu_559_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_168 <= add_ln300_fu_565_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_168 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            message_done_1_fu_172 <= message_done;
        end else if (((tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            message_done_1_fu_172 <= message_done_2_fu_782_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln300_reg_815 <= trunc_ln300_fu_571_p1;
    end
end

always @ (*) begin
    if (((icmp_ln300_fu_559_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 6'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_168;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_stream_TDATA_blk_n = input_stream_TVALID;
    end else begin
        input_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_stream_TREADY = 1'b1;
    end else begin
        input_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln300_fu_559_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        message_done_1_out_ap_vld = 1'b1;
    end else begin
        message_done_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd10))) begin
        state_10_o = state_25_fu_695_p2;
    end else begin
        state_10_o = state_10_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd10))) begin
        state_10_o_ap_vld = 1'b1;
    end else begin
        state_10_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd11))) begin
        state_11_o = state_25_fu_695_p2;
    end else begin
        state_11_o = state_11_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd11))) begin
        state_11_o_ap_vld = 1'b1;
    end else begin
        state_11_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd12))) begin
        state_12_o = state_25_fu_695_p2;
    end else begin
        state_12_o = state_12_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd12))) begin
        state_12_o_ap_vld = 1'b1;
    end else begin
        state_12_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd13))) begin
        state_13_o = state_25_fu_695_p2;
    end else begin
        state_13_o = state_13_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd13))) begin
        state_13_o_ap_vld = 1'b1;
    end else begin
        state_13_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd14))) begin
        state_14_o = state_25_fu_695_p2;
    end else begin
        state_14_o = state_14_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd14))) begin
        state_14_o_ap_vld = 1'b1;
    end else begin
        state_14_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd15))) begin
        state_15_o = state_25_fu_695_p2;
    end else begin
        state_15_o = state_15_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd15))) begin
        state_15_o_ap_vld = 1'b1;
    end else begin
        state_15_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd16))) begin
        state_16_o = state_25_fu_695_p2;
    end else begin
        state_16_o = state_16_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd16))) begin
        state_16_o_ap_vld = 1'b1;
    end else begin
        state_16_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd17))) begin
        state_17_o = state_25_fu_695_p2;
    end else begin
        state_17_o = state_17_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd17))) begin
        state_17_o_ap_vld = 1'b1;
    end else begin
        state_17_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd18))) begin
        state_18_o = state_25_fu_695_p2;
    end else begin
        state_18_o = state_18_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd18))) begin
        state_18_o_ap_vld = 1'b1;
    end else begin
        state_18_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd19))) begin
        state_19_o = state_25_fu_695_p2;
    end else begin
        state_19_o = state_19_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd19))) begin
        state_19_o_ap_vld = 1'b1;
    end else begin
        state_19_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd1))) begin
        state_1_o = state_25_fu_695_p2;
    end else begin
        state_1_o = state_1_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd1))) begin
        state_1_o_ap_vld = 1'b1;
    end else begin
        state_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd20))) begin
        state_20_o = state_25_fu_695_p2;
    end else begin
        state_20_o = state_20_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd20))) begin
        state_20_o_ap_vld = 1'b1;
    end else begin
        state_20_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd21))) begin
        state_21_o = state_25_fu_695_p2;
    end else begin
        state_21_o = state_21_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd21))) begin
        state_21_o_ap_vld = 1'b1;
    end else begin
        state_21_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd22))) begin
        state_22_o = state_25_fu_695_p2;
    end else begin
        state_22_o = state_22_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd22))) begin
        state_22_o_ap_vld = 1'b1;
    end else begin
        state_22_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd23))) begin
        state_23_o = state_25_fu_695_p2;
    end else begin
        state_23_o = state_23_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd23))) begin
        state_23_o_ap_vld = 1'b1;
    end else begin
        state_23_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd24))) begin
        state_24_o = state_25_fu_695_p2;
    end else begin
        state_24_o = state_24_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd24))) begin
        state_24_o_ap_vld = 1'b1;
    end else begin
        state_24_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd2))) begin
        state_2_o = state_25_fu_695_p2;
    end else begin
        state_2_o = state_2_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd2))) begin
        state_2_o_ap_vld = 1'b1;
    end else begin
        state_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd3))) begin
        state_3_o = state_25_fu_695_p2;
    end else begin
        state_3_o = state_3_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd3))) begin
        state_3_o_ap_vld = 1'b1;
    end else begin
        state_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd4))) begin
        state_4_o = state_25_fu_695_p2;
    end else begin
        state_4_o = state_4_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd4))) begin
        state_4_o_ap_vld = 1'b1;
    end else begin
        state_4_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd5))) begin
        state_5_o = state_25_fu_695_p2;
    end else begin
        state_5_o = state_5_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd5))) begin
        state_5_o_ap_vld = 1'b1;
    end else begin
        state_5_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd6))) begin
        state_6_o = state_25_fu_695_p2;
    end else begin
        state_6_o = state_6_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd6))) begin
        state_6_o_ap_vld = 1'b1;
    end else begin
        state_6_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd7))) begin
        state_7_o = state_25_fu_695_p2;
    end else begin
        state_7_o = state_7_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd7))) begin
        state_7_o_ap_vld = 1'b1;
    end else begin
        state_7_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd8))) begin
        state_8_o = state_25_fu_695_p2;
    end else begin
        state_8_o = state_8_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd8))) begin
        state_8_o_ap_vld = 1'b1;
    end else begin
        state_8_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd9))) begin
        state_9_o = state_25_fu_695_p2;
    end else begin
        state_9_o = state_9_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd9))) begin
        state_9_o_ap_vld = 1'b1;
    end else begin
        state_9_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd0))) begin
        state_o = state_25_fu_695_p2;
    end else begin
        state_o = state_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln300_reg_815 == 5'd0))) begin
        state_o_ap_vld = 1'b1;
    end else begin
        state_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln300_fu_565_p2 = (ap_sig_allocacmp_i_2 + 6'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp1 = ((tmp_1_nbreadreq_fu_188_p6 == 1'd1) & (input_stream_TVALID == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln300_fu_559_p2 = ((ap_sig_allocacmp_i_2 == trunc_ln1) ? 1'b1 : 1'b0);

assign message_done_1_out = message_done_1_fu_172;

assign message_done_2_fu_782_p2 = (message_done_1_fu_172 | input_stream_TLAST);

assign state_25_fu_695_p2 = (tmp_2_fu_588_p53 ^ input_stream_TDATA);

assign tmp_1_nbreadreq_fu_188_p6 = input_stream_TVALID;

assign tmp_2_fu_588_p51 = 'bx;

assign trunc_ln300_fu_571_p1 = ap_sig_allocacmp_i_2[4:0];

endmodule //keccak_top_keccak_top_Pipeline_ABSORB_BLOCK
