-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity keccak_top_keccak_top_Pipeline_SQUEEZE_BLOCK is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    output_stream_TREADY : IN STD_LOGIC;
    output_remaining : IN STD_LOGIC_VECTOR (30 downto 0);
    trunc_ln4 : IN STD_LOGIC_VECTOR (5 downto 0);
    state_5217 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_1_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_2_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_3_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_4_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_5_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_6_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_7_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_8_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_9_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_10_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_11_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_12_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_13_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_14_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_15_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_16_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_17_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_18_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_19_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_20_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_21_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_22_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_23_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    state_24_5 : IN STD_LOGIC_VECTOR (63 downto 0);
    output_stream_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_stream_TVALID : OUT STD_LOGIC;
    output_stream_TKEEP : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_stream_TSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_remaining_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_remaining_1_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of keccak_top_keccak_top_Pipeline_SQUEEZE_BLOCK is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln310_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal output_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_0_fu_404_p53 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_0_reg_709 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln315_fu_497_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln315_reg_714 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_remaining_2_fu_511_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_remaining_2_reg_719 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln319_fu_523_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln319_reg_724 : STD_LOGIC_VECTOR (7 downto 0);
    signal output_remaining_1_fu_176 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal output_remaining_cast_fu_369_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_fu_180 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln310_fu_391_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal select_ln319_fu_548_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal p_0_fu_404_p51 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_0_fu_404_p52 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_487_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal bytes_out_fu_503_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln319_fu_517_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln319_fu_543_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal p_0_fu_404_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p5 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p7 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p9 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p11 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p13 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p15 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p17 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p19 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p21 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p23 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p25 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p27 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p29 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p31 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p33 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p35 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p37 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p39 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p41 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p43 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p45 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p47 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_fu_404_p49 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component keccak_top_sparsemux_51_5_64_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (4 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (4 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (4 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (4 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (4 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (4 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (4 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (4 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (4 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (4 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (4 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (4 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (4 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (4 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (4 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (4 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (4 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (4 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (4 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (4 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (4 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (4 downto 0);
        din21_WIDTH : INTEGER;
        CASE22 : STD_LOGIC_VECTOR (4 downto 0);
        din22_WIDTH : INTEGER;
        CASE23 : STD_LOGIC_VECTOR (4 downto 0);
        din23_WIDTH : INTEGER;
        CASE24 : STD_LOGIC_VECTOR (4 downto 0);
        din24_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        din2 : IN STD_LOGIC_VECTOR (63 downto 0);
        din3 : IN STD_LOGIC_VECTOR (63 downto 0);
        din4 : IN STD_LOGIC_VECTOR (63 downto 0);
        din5 : IN STD_LOGIC_VECTOR (63 downto 0);
        din6 : IN STD_LOGIC_VECTOR (63 downto 0);
        din7 : IN STD_LOGIC_VECTOR (63 downto 0);
        din8 : IN STD_LOGIC_VECTOR (63 downto 0);
        din9 : IN STD_LOGIC_VECTOR (63 downto 0);
        din10 : IN STD_LOGIC_VECTOR (63 downto 0);
        din11 : IN STD_LOGIC_VECTOR (63 downto 0);
        din12 : IN STD_LOGIC_VECTOR (63 downto 0);
        din13 : IN STD_LOGIC_VECTOR (63 downto 0);
        din14 : IN STD_LOGIC_VECTOR (63 downto 0);
        din15 : IN STD_LOGIC_VECTOR (63 downto 0);
        din16 : IN STD_LOGIC_VECTOR (63 downto 0);
        din17 : IN STD_LOGIC_VECTOR (63 downto 0);
        din18 : IN STD_LOGIC_VECTOR (63 downto 0);
        din19 : IN STD_LOGIC_VECTOR (63 downto 0);
        din20 : IN STD_LOGIC_VECTOR (63 downto 0);
        din21 : IN STD_LOGIC_VECTOR (63 downto 0);
        din22 : IN STD_LOGIC_VECTOR (63 downto 0);
        din23 : IN STD_LOGIC_VECTOR (63 downto 0);
        din24 : IN STD_LOGIC_VECTOR (63 downto 0);
        def : IN STD_LOGIC_VECTOR (63 downto 0);
        sel : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component keccak_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_51_5_64_1_1_U27 : component keccak_top_sparsemux_51_5_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00000",
        din0_WIDTH => 64,
        CASE1 => "00001",
        din1_WIDTH => 64,
        CASE2 => "00010",
        din2_WIDTH => 64,
        CASE3 => "00011",
        din3_WIDTH => 64,
        CASE4 => "00100",
        din4_WIDTH => 64,
        CASE5 => "00101",
        din5_WIDTH => 64,
        CASE6 => "00110",
        din6_WIDTH => 64,
        CASE7 => "00111",
        din7_WIDTH => 64,
        CASE8 => "01000",
        din8_WIDTH => 64,
        CASE9 => "01001",
        din9_WIDTH => 64,
        CASE10 => "01010",
        din10_WIDTH => 64,
        CASE11 => "01011",
        din11_WIDTH => 64,
        CASE12 => "01100",
        din12_WIDTH => 64,
        CASE13 => "01101",
        din13_WIDTH => 64,
        CASE14 => "01110",
        din14_WIDTH => 64,
        CASE15 => "01111",
        din15_WIDTH => 64,
        CASE16 => "10000",
        din16_WIDTH => 64,
        CASE17 => "10001",
        din17_WIDTH => 64,
        CASE18 => "10010",
        din18_WIDTH => 64,
        CASE19 => "10011",
        din19_WIDTH => 64,
        CASE20 => "10100",
        din20_WIDTH => 64,
        CASE21 => "10101",
        din21_WIDTH => 64,
        CASE22 => "10110",
        din22_WIDTH => 64,
        CASE23 => "10111",
        din23_WIDTH => 64,
        CASE24 => "11000",
        din24_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 5,
        dout_WIDTH => 64)
    port map (
        din0 => state_5217,
        din1 => state_1_5,
        din2 => state_2_5,
        din3 => state_3_5,
        din4 => state_4_5,
        din5 => state_5_5,
        din6 => state_6_5,
        din7 => state_7_5,
        din8 => state_8_5,
        din9 => state_9_5,
        din10 => state_10_5,
        din11 => state_11_5,
        din12 => state_12_5,
        din13 => state_13_5,
        din14 => state_14_5,
        din15 => state_15_5,
        din16 => state_16_5,
        din17 => state_17_5,
        din18 => state_18_5,
        din19 => state_19_5,
        din20 => state_20_5,
        din21 => state_21_5,
        din22 => state_22_5,
        din23 => state_23_5,
        din24 => state_24_5,
        def => p_0_fu_404_p51,
        sel => p_0_fu_404_p52,
        dout => p_0_fu_404_p53);

    flow_control_loop_pipe_sequential_init_U : component keccak_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_180_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_180 <= ap_const_lv6_0;
                elsif (((icmp_ln310_fu_386_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_fu_180 <= add_ln310_fu_391_p2;
                end if;
            end if; 
        end if;
    end process;

    output_remaining_1_fu_176_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    output_remaining_1_fu_176 <= output_remaining_cast_fu_369_p1;
                elsif (((icmp_ln310_fu_386_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    output_remaining_1_fu_176 <= output_remaining_2_fu_511_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln315_reg_714 <= icmp_ln315_fu_497_p2;
                output_remaining_2_reg_719 <= output_remaining_2_fu_511_p2;
                p_0_reg_709 <= p_0_fu_404_p53;
                trunc_ln319_reg_724 <= trunc_ln319_fu_523_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln310_fu_391_p2 <= std_logic_vector(unsigned(i_fu_180) + unsigned(ap_const_lv6_1));
    add_ln319_fu_543_p2 <= std_logic_vector(unsigned(trunc_ln319_reg_724) + unsigned(ap_const_lv8_FF));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, output_stream_TREADY)
    begin
                ap_block_pp0_stage0_01001 <= ((output_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, output_stream_TREADY)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((output_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, output_stream_TREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((output_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, output_stream_TREADY)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((output_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, output_stream_TREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((output_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln310_fu_386_p2)
    begin
        if (((icmp_ln310_fu_386_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    bytes_out_fu_503_p3 <= 
        ap_const_lv32_8 when (icmp_ln315_fu_497_p2(0) = '1') else 
        output_remaining_1_fu_176;
    icmp_ln310_fu_386_p2 <= "1" when (i_fu_180 = trunc_ln4) else "0";
    icmp_ln315_fu_497_p2 <= "1" when (signed(tmp_fu_487_p4) > signed(ap_const_lv29_0)) else "0";
    output_remaining_1_out <= output_remaining_1_fu_176;

    output_remaining_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln310_fu_386_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln310_fu_386_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            output_remaining_1_out_ap_vld <= ap_const_logic_1;
        else 
            output_remaining_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_remaining_2_fu_511_p2 <= std_logic_vector(unsigned(output_remaining_1_fu_176) - unsigned(bytes_out_fu_503_p3));
    output_remaining_cast_fu_369_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(output_remaining),32));
    output_stream_TDATA <= p_0_reg_709;

    output_stream_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, output_stream_TREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_stream_TDATA_blk_n <= output_stream_TREADY;
        else 
            output_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    output_stream_TKEEP <= select_ln319_fu_548_p3;
    output_stream_TLAST <= "1" when (signed(output_remaining_2_reg_719) < signed(ap_const_lv32_1)) else "0";
    output_stream_TSTRB <= select_ln319_fu_548_p3;

    output_stream_TVALID_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_stream_TVALID <= ap_const_logic_1;
        else 
            output_stream_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    p_0_fu_404_p51 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    p_0_fu_404_p52 <= i_fu_180(5 - 1 downto 0);
    select_ln319_fu_548_p3 <= 
        ap_const_lv8_FF when (icmp_ln315_reg_714(0) = '1') else 
        add_ln319_fu_543_p2;
    shl_ln319_fu_517_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv32_1),to_integer(unsigned('0' & bytes_out_fu_503_p3(31-1 downto 0)))));
    tmp_fu_487_p4 <= output_remaining_1_fu_176(31 downto 3);
    trunc_ln319_fu_523_p1 <= shl_ln319_fu_517_p2(8 - 1 downto 0);
end behav;
