# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_zynq_ultra_ps_e_0_0/top_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==top_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/top/ip/top_proc_sys_reset_0_0/top_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_proc_sys_reset_0_0 || ORIG_REF_NAME==top_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/top/ip/top_smartconnect_0_0/top_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_smartconnect_0_0 || ORIG_REF_NAME==top_smartconnect_0_0} -quiet] -quiet

# IP: bd/top/ip/top_keccak_core_0_0/top_keccak_core_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_keccak_core_0_0 || ORIG_REF_NAME==top_keccak_core_0_0} -quiet] -quiet

# XDC: c:/Users/jakub/projects/rim-projekt/keccak/keccak.gen/sources_1/bd/top/top_ooc.xdc
