-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity keccak_top_keccak_f1600 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    state_0_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_1_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_2_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_3_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_4_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_5_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_6_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_7_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_8_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_9_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_10_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_11_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_1213_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_13_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_14_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_15_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_16_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_17_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_18_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_19_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_20_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_21_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_22_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_2325_read : IN STD_LOGIC_VECTOR (63 downto 0);
    state_24_read : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of keccak_top_keccak_f1600 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_3A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv32_3D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111101";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln149_fu_628_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal RC_TABLE_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal RC_TABLE_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln149_fu_640_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal state_0_0_fu_228 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln137_fu_2053_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_0_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal state_5_0_fu_232 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_6_fu_1705_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_5_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_10_0_fu_236 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_16_fu_1795_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_10_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_1549_0_fu_240 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_26_fu_1885_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_1549_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_20_0_fu_244 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_36_fu_1975_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_20_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_1_0_fu_248 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_1_fu_1663_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_1_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_6_0_fu_252 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_8_fu_1723_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_6_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_11_0_fu_256 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_18_fu_1813_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_11_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_16_0_fu_260 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_28_fu_1903_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_16_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_21_0_fu_264 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_38_fu_1993_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_21_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_2_0_fu_268 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_3_fu_1681_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_2_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_7_0_fu_272 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_10_fu_1741_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_7_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_1213_0_fu_276 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_20_fu_1831_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_1213_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_17_0_fu_280 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_30_fu_1921_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_17_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_22_0_fu_284 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_40_fu_2011_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_22_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_3_0_fu_288 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_4_fu_1687_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_3_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_8_0_fu_292 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_12_fu_1759_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_8_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_13_0_fu_296 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_22_fu_1849_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_13_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_18_0_fu_300 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_32_fu_1939_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_18_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_2325_0_fu_304 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_42_fu_2029_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_2325_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_4_0_fu_308 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal or_ln22_27_fu_1637_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_4_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_9_0_fu_312 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_14_fu_1777_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_9_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_14_0_fu_316 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_24_fu_1867_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_14_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_19_0_fu_320 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_34_fu_1957_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_19_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal state_24_0_fu_324 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal xor_ln127_44_fu_2047_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_state_24_0_load_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal round_fu_328 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln149_fu_634_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_round_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal RC_TABLE_ce0_local : STD_LOGIC;
    signal xor_ln50_1_fu_731_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln50_2_fu_737_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln50_fu_725_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln50_5_fu_755_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln50_6_fu_761_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln50_4_fu_749_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln50_9_fu_779_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln50_10_fu_785_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln50_8_fu_773_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln50_13_fu_803_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln50_14_fu_809_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln50_12_fu_797_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln50_17_fu_827_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln50_18_fu_833_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln50_16_fu_821_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_fu_767_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_fu_845_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_fu_849_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln_fu_857_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_3_fu_839_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_1_fu_791_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_1_fu_871_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_3_fu_875_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_4_fu_743_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_1_fu_883_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_2_fu_815_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_2_fu_897_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_4_fu_901_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln22_2_fu_909_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_3_fu_923_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_5_fu_927_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln22_3_fu_935_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_4_fu_949_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_6_fu_953_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln22_4_fu_961_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln57_1_fu_891_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln57_2_fu_917_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln57_3_fu_943_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln57_4_fu_969_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln57_fu_865_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_5_fu_975_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_5_fu_1119_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_7_fu_1123_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_6_fu_981_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_6_fu_1139_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal lshr_ln22_6_fu_1143_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal x_7_fu_987_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_7_fu_1161_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal lshr_ln22_7_fu_1165_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal x_8_fu_993_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_8_fu_1183_p1 : STD_LOGIC_VECTOR (36 downto 0);
    signal lshr_ln22_8_fu_1187_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal x_9_fu_999_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_9_fu_1205_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal lshr_ln22_9_fu_1209_p4 : STD_LOGIC_VECTOR (35 downto 0);
    signal x_10_fu_1005_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_10_fu_1227_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal lshr_ln22_s_fu_1231_p4 : STD_LOGIC_VECTOR (43 downto 0);
    signal x_11_fu_1011_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_11_fu_1249_p1 : STD_LOGIC_VECTOR (57 downto 0);
    signal lshr_ln22_1_fu_1253_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal x_12_fu_1017_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_12_fu_1271_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal lshr_ln22_2_fu_1275_p4 : STD_LOGIC_VECTOR (54 downto 0);
    signal x_13_fu_1023_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_13_fu_1293_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal lshr_ln22_3_fu_1297_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal x_14_fu_1029_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_14_fu_1315_p1 : STD_LOGIC_VECTOR (60 downto 0);
    signal lshr_ln22_4_fu_1319_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_15_fu_1035_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_15_fu_1337_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal lshr_ln22_5_fu_1341_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_16_fu_1041_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_16_fu_1359_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal lshr_ln22_10_fu_1363_p4 : STD_LOGIC_VECTOR (42 downto 0);
    signal x_17_fu_1047_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_17_fu_1381_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal lshr_ln22_11_fu_1385_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal x_18_fu_1053_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_18_fu_1403_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal lshr_ln22_12_fu_1407_p4 : STD_LOGIC_VECTOR (38 downto 0);
    signal x_19_fu_1059_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_19_fu_1425_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal lshr_ln22_13_fu_1429_p4 : STD_LOGIC_VECTOR (40 downto 0);
    signal x_20_fu_1065_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_20_fu_1447_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal lshr_ln22_14_fu_1451_p4 : STD_LOGIC_VECTOR (44 downto 0);
    signal x_21_fu_1071_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_21_fu_1469_p1 : STD_LOGIC_VECTOR (48 downto 0);
    signal lshr_ln22_15_fu_1473_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal x_22_fu_1077_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_22_fu_1491_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal lshr_ln22_16_fu_1495_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal x_23_fu_1083_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_23_fu_1513_p1 : STD_LOGIC_VECTOR (55 downto 0);
    signal lshr_ln22_17_fu_1517_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_24_fu_1089_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_24_fu_1535_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal lshr_ln22_18_fu_1539_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal x_25_fu_1095_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_25_fu_1557_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal lshr_ln22_19_fu_1561_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal x_26_fu_1101_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_26_fu_1579_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln22_20_fu_1583_p4 : STD_LOGIC_VECTOR (60 downto 0);
    signal x_27_fu_1107_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_27_fu_1601_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln22_21_fu_1605_p4 : STD_LOGIC_VECTOR (55 downto 0);
    signal x_28_fu_1113_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln22_28_fu_1623_p1 : STD_LOGIC_VECTOR (49 downto 0);
    signal lshr_ln22_22_fu_1627_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal or_ln22_15_fu_1373_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_s_fu_1241_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_fu_1645_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_21_fu_1505_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_fu_1657_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_2_fu_1669_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_1_fu_1675_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_12_fu_1307_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_13_fu_1329_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_5_fu_1693_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_2_fu_1699_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_7_fu_1175_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_19_fu_1461_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_7_fu_1711_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_3_fu_1717_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_25_fu_1593_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_9_fu_1729_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_4_fu_1735_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_11_fu_1747_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_5_fu_1753_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_13_fu_1765_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_6_fu_1771_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_10_fu_1263_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_16_fu_1395_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_15_fu_1783_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_5_fu_1131_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_7_fu_1789_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_22_fu_1527_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_17_fu_1801_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_8_fu_1807_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_23_fu_1549_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_19_fu_1819_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_9_fu_1825_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_21_fu_1837_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_10_fu_1843_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_23_fu_1855_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_11_fu_1861_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_9_fu_1219_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_14_fu_1351_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_25_fu_1873_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_8_fu_1197_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_12_fu_1879_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_20_fu_1483_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_27_fu_1891_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_13_fu_1897_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_26_fu_1615_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_29_fu_1909_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_14_fu_1915_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_31_fu_1927_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_15_fu_1933_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_33_fu_1945_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_16_fu_1951_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_11_fu_1285_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_17_fu_1417_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_35_fu_1963_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_17_fu_1969_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_6_fu_1153_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_18_fu_1439_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_37_fu_1981_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_18_fu_1987_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln22_24_fu_1571_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_39_fu_1999_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_19_fu_2005_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_41_fu_2017_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_20_fu_2023_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln127_43_fu_2035_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln127_21_fu_2041_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln127_fu_1651_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component keccak_top_keccak_f1600_RC_TABLE_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component keccak_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    RC_TABLE_U : component keccak_top_keccak_f1600_RC_TABLE_ROM_AUTO_1R
    generic map (
        DataWidth => 64,
        AddressRange => 24,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => RC_TABLE_address0,
        ce0 => RC_TABLE_ce0_local,
        q0 => RC_TABLE_q0);

    flow_control_loop_pipe_sequential_init_U : component keccak_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    round_fu_328_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln149_fu_628_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    round_fu_328 <= add_ln149_fu_634_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    round_fu_328 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    state_0_0_fu_228_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_0_0_fu_228 <= state_0_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_0_0_fu_228 <= xor_ln137_fu_2053_p2;
                end if;
            end if; 
        end if;
    end process;

    state_10_0_fu_236_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_10_0_fu_236 <= state_10_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_10_0_fu_236 <= xor_ln127_16_fu_1795_p2;
                end if;
            end if; 
        end if;
    end process;

    state_11_0_fu_256_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_11_0_fu_256 <= state_11_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_11_0_fu_256 <= xor_ln127_18_fu_1813_p2;
                end if;
            end if; 
        end if;
    end process;

    state_1213_0_fu_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_1213_0_fu_276 <= state_1213_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_1213_0_fu_276 <= xor_ln127_20_fu_1831_p2;
                end if;
            end if; 
        end if;
    end process;

    state_13_0_fu_296_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_13_0_fu_296 <= state_13_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_13_0_fu_296 <= xor_ln127_22_fu_1849_p2;
                end if;
            end if; 
        end if;
    end process;

    state_14_0_fu_316_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_14_0_fu_316 <= state_14_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_14_0_fu_316 <= xor_ln127_24_fu_1867_p2;
                end if;
            end if; 
        end if;
    end process;

    state_1549_0_fu_240_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_1549_0_fu_240 <= state_15_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_1549_0_fu_240 <= xor_ln127_26_fu_1885_p2;
                end if;
            end if; 
        end if;
    end process;

    state_16_0_fu_260_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_16_0_fu_260 <= state_16_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_16_0_fu_260 <= xor_ln127_28_fu_1903_p2;
                end if;
            end if; 
        end if;
    end process;

    state_17_0_fu_280_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_17_0_fu_280 <= state_17_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_17_0_fu_280 <= xor_ln127_30_fu_1921_p2;
                end if;
            end if; 
        end if;
    end process;

    state_18_0_fu_300_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_18_0_fu_300 <= state_18_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_18_0_fu_300 <= xor_ln127_32_fu_1939_p2;
                end if;
            end if; 
        end if;
    end process;

    state_19_0_fu_320_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_19_0_fu_320 <= state_19_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_19_0_fu_320 <= xor_ln127_34_fu_1957_p2;
                end if;
            end if; 
        end if;
    end process;

    state_1_0_fu_248_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_1_0_fu_248 <= state_1_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_1_0_fu_248 <= xor_ln127_1_fu_1663_p2;
                end if;
            end if; 
        end if;
    end process;

    state_20_0_fu_244_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_20_0_fu_244 <= state_20_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_20_0_fu_244 <= xor_ln127_36_fu_1975_p2;
                end if;
            end if; 
        end if;
    end process;

    state_21_0_fu_264_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_21_0_fu_264 <= state_21_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_21_0_fu_264 <= xor_ln127_38_fu_1993_p2;
                end if;
            end if; 
        end if;
    end process;

    state_22_0_fu_284_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_22_0_fu_284 <= state_22_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_22_0_fu_284 <= xor_ln127_40_fu_2011_p2;
                end if;
            end if; 
        end if;
    end process;

    state_2325_0_fu_304_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_2325_0_fu_304 <= state_2325_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_2325_0_fu_304 <= xor_ln127_42_fu_2029_p2;
                end if;
            end if; 
        end if;
    end process;

    state_24_0_fu_324_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_24_0_fu_324 <= state_24_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_24_0_fu_324 <= xor_ln127_44_fu_2047_p2;
                end if;
            end if; 
        end if;
    end process;

    state_2_0_fu_268_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_2_0_fu_268 <= state_2_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_2_0_fu_268 <= xor_ln127_3_fu_1681_p2;
                end if;
            end if; 
        end if;
    end process;

    state_3_0_fu_288_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_3_0_fu_288 <= state_3_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_3_0_fu_288 <= xor_ln127_4_fu_1687_p2;
                end if;
            end if; 
        end if;
    end process;

    state_4_0_fu_308_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_4_0_fu_308 <= state_4_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_4_0_fu_308 <= or_ln22_27_fu_1637_p3;
                end if;
            end if; 
        end if;
    end process;

    state_5_0_fu_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_5_0_fu_232 <= state_5_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_5_0_fu_232 <= xor_ln127_6_fu_1705_p2;
                end if;
            end if; 
        end if;
    end process;

    state_6_0_fu_252_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_6_0_fu_252 <= state_6_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_6_0_fu_252 <= xor_ln127_8_fu_1723_p2;
                end if;
            end if; 
        end if;
    end process;

    state_7_0_fu_272_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_7_0_fu_272 <= state_7_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_7_0_fu_272 <= xor_ln127_10_fu_1741_p2;
                end if;
            end if; 
        end if;
    end process;

    state_8_0_fu_292_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_8_0_fu_292 <= state_8_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_8_0_fu_292 <= xor_ln127_12_fu_1759_p2;
                end if;
            end if; 
        end if;
    end process;

    state_9_0_fu_312_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    state_9_0_fu_312 <= state_9_read;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    state_9_0_fu_312 <= xor_ln127_14_fu_1777_p2;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    RC_TABLE_address0 <= zext_ln149_fu_640_p1(5 - 1 downto 0);

    RC_TABLE_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            RC_TABLE_ce0_local <= ap_const_logic_1;
        else 
            RC_TABLE_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln149_fu_634_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_round_1) + unsigned(ap_const_lv5_1));
    and_ln127_10_fu_1843_p2 <= (xor_ln127_21_fu_1837_p2 and or_ln22_5_fu_1131_p3);
    and_ln127_11_fu_1861_p2 <= (xor_ln127_23_fu_1855_p2 and or_ln22_10_fu_1263_p3);
    and_ln127_12_fu_1879_p2 <= (xor_ln127_25_fu_1873_p2 and or_ln22_14_fu_1351_p3);
    and_ln127_13_fu_1897_p2 <= (xor_ln127_27_fu_1891_p2 and or_ln22_20_fu_1483_p3);
    and_ln127_14_fu_1915_p2 <= (xor_ln127_29_fu_1909_p2 and or_ln22_26_fu_1615_p3);
    and_ln127_15_fu_1933_p2 <= (xor_ln127_31_fu_1927_p2 and or_ln22_8_fu_1197_p3);
    and_ln127_16_fu_1951_p2 <= (xor_ln127_33_fu_1945_p2 and or_ln22_9_fu_1219_p3);
    and_ln127_17_fu_1969_p2 <= (xor_ln127_35_fu_1963_p2 and or_ln22_17_fu_1417_p3);
    and_ln127_18_fu_1987_p2 <= (xor_ln127_37_fu_1981_p2 and or_ln22_18_fu_1439_p3);
    and_ln127_19_fu_2005_p2 <= (xor_ln127_39_fu_1999_p2 and or_ln22_24_fu_1571_p3);
    and_ln127_1_fu_1675_p2 <= (xor_ln127_2_fu_1669_p2 and or_ln22_27_fu_1637_p3);
    and_ln127_20_fu_2023_p2 <= (xor_ln127_41_fu_2017_p2 and or_ln22_6_fu_1153_p3);
    and_ln127_21_fu_2041_p2 <= (xor_ln127_43_fu_2035_p2 and or_ln22_11_fu_1285_p3);
    and_ln127_2_fu_1699_p2 <= (xor_ln127_5_fu_1693_p2 and or_ln22_13_fu_1329_p3);
    and_ln127_3_fu_1717_p2 <= (xor_ln127_7_fu_1711_p2 and or_ln22_19_fu_1461_p3);
    and_ln127_4_fu_1735_p2 <= (xor_ln127_9_fu_1729_p2 and or_ln22_25_fu_1593_p3);
    and_ln127_5_fu_1753_p2 <= (xor_ln127_11_fu_1747_p2 and or_ln22_7_fu_1175_p3);
    and_ln127_6_fu_1771_p2 <= (xor_ln127_13_fu_1765_p2 and or_ln22_12_fu_1307_p3);
    and_ln127_7_fu_1789_p2 <= (xor_ln127_15_fu_1783_p2 and or_ln22_16_fu_1395_p3);
    and_ln127_8_fu_1807_p2 <= (xor_ln127_17_fu_1801_p2 and or_ln22_22_fu_1527_p3);
    and_ln127_9_fu_1825_p2 <= (xor_ln127_19_fu_1819_p2 and or_ln22_23_fu_1549_p3);
    and_ln127_fu_1657_p2 <= (xor_ln127_fu_1645_p2 and or_ln22_21_fu_1505_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln149_fu_628_p2)
    begin
        if (((icmp_ln149_fu_628_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= ap_sig_allocacmp_state_0_0_load_1;
    ap_return_1 <= ap_sig_allocacmp_state_1_0_load_1;
    ap_return_10 <= ap_sig_allocacmp_state_10_0_load_1;
    ap_return_11 <= ap_sig_allocacmp_state_11_0_load_1;
    ap_return_12 <= ap_sig_allocacmp_state_1213_0_load_1;
    ap_return_13 <= ap_sig_allocacmp_state_13_0_load_1;
    ap_return_14 <= ap_sig_allocacmp_state_14_0_load_1;
    ap_return_15 <= ap_sig_allocacmp_state_1549_0_load_1;
    ap_return_16 <= ap_sig_allocacmp_state_16_0_load_1;
    ap_return_17 <= ap_sig_allocacmp_state_17_0_load_1;
    ap_return_18 <= ap_sig_allocacmp_state_18_0_load_1;
    ap_return_19 <= ap_sig_allocacmp_state_19_0_load_1;
    ap_return_2 <= ap_sig_allocacmp_state_2_0_load_1;
    ap_return_20 <= ap_sig_allocacmp_state_20_0_load_1;
    ap_return_21 <= ap_sig_allocacmp_state_21_0_load_1;
    ap_return_22 <= ap_sig_allocacmp_state_22_0_load_1;
    ap_return_23 <= ap_sig_allocacmp_state_2325_0_load_1;
    ap_return_24 <= ap_sig_allocacmp_state_24_0_load_1;
    ap_return_3 <= ap_sig_allocacmp_state_3_0_load_1;
    ap_return_4 <= ap_sig_allocacmp_state_4_0_load_1;
    ap_return_5 <= ap_sig_allocacmp_state_5_0_load_1;
    ap_return_6 <= ap_sig_allocacmp_state_6_0_load_1;
    ap_return_7 <= ap_sig_allocacmp_state_7_0_load_1;
    ap_return_8 <= ap_sig_allocacmp_state_8_0_load_1;
    ap_return_9 <= ap_sig_allocacmp_state_9_0_load_1;

    ap_sig_allocacmp_round_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, round_fu_328)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_round_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_round_1 <= round_fu_328;
        end if; 
    end process;


    ap_sig_allocacmp_state_0_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_0_read, ap_block_pp0_stage0, state_0_0_fu_228, xor_ln137_fu_2053_p2, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_0_0_load_1 <= state_0_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_0_0_load_1 <= xor_ln137_fu_2053_p2;
            else 
                ap_sig_allocacmp_state_0_0_load_1 <= state_0_0_fu_228;
            end if;
        else 
            ap_sig_allocacmp_state_0_0_load_1 <= state_0_0_fu_228;
        end if; 
    end process;


    ap_sig_allocacmp_state_10_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_10_read, ap_block_pp0_stage0, ap_loop_init, state_10_0_fu_236, xor_ln127_16_fu_1795_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_10_0_load_1 <= state_10_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_10_0_load_1 <= xor_ln127_16_fu_1795_p2;
            else 
                ap_sig_allocacmp_state_10_0_load_1 <= state_10_0_fu_236;
            end if;
        else 
            ap_sig_allocacmp_state_10_0_load_1 <= state_10_0_fu_236;
        end if; 
    end process;


    ap_sig_allocacmp_state_11_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_11_read, ap_block_pp0_stage0, ap_loop_init, state_11_0_fu_256, xor_ln127_18_fu_1813_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_11_0_load_1 <= state_11_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_11_0_load_1 <= xor_ln127_18_fu_1813_p2;
            else 
                ap_sig_allocacmp_state_11_0_load_1 <= state_11_0_fu_256;
            end if;
        else 
            ap_sig_allocacmp_state_11_0_load_1 <= state_11_0_fu_256;
        end if; 
    end process;


    ap_sig_allocacmp_state_1213_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_1213_read, ap_block_pp0_stage0, ap_loop_init, state_1213_0_fu_276, xor_ln127_20_fu_1831_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_1213_0_load_1 <= state_1213_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_1213_0_load_1 <= xor_ln127_20_fu_1831_p2;
            else 
                ap_sig_allocacmp_state_1213_0_load_1 <= state_1213_0_fu_276;
            end if;
        else 
            ap_sig_allocacmp_state_1213_0_load_1 <= state_1213_0_fu_276;
        end if; 
    end process;


    ap_sig_allocacmp_state_13_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_13_read, ap_block_pp0_stage0, ap_loop_init, state_13_0_fu_296, xor_ln127_22_fu_1849_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_13_0_load_1 <= state_13_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_13_0_load_1 <= xor_ln127_22_fu_1849_p2;
            else 
                ap_sig_allocacmp_state_13_0_load_1 <= state_13_0_fu_296;
            end if;
        else 
            ap_sig_allocacmp_state_13_0_load_1 <= state_13_0_fu_296;
        end if; 
    end process;


    ap_sig_allocacmp_state_14_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_14_read, ap_block_pp0_stage0, ap_loop_init, state_14_0_fu_316, xor_ln127_24_fu_1867_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_14_0_load_1 <= state_14_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_14_0_load_1 <= xor_ln127_24_fu_1867_p2;
            else 
                ap_sig_allocacmp_state_14_0_load_1 <= state_14_0_fu_316;
            end if;
        else 
            ap_sig_allocacmp_state_14_0_load_1 <= state_14_0_fu_316;
        end if; 
    end process;


    ap_sig_allocacmp_state_1549_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_15_read, ap_block_pp0_stage0, ap_loop_init, state_1549_0_fu_240, xor_ln127_26_fu_1885_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_1549_0_load_1 <= state_15_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_1549_0_load_1 <= xor_ln127_26_fu_1885_p2;
            else 
                ap_sig_allocacmp_state_1549_0_load_1 <= state_1549_0_fu_240;
            end if;
        else 
            ap_sig_allocacmp_state_1549_0_load_1 <= state_1549_0_fu_240;
        end if; 
    end process;


    ap_sig_allocacmp_state_16_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_16_read, ap_block_pp0_stage0, ap_loop_init, state_16_0_fu_260, xor_ln127_28_fu_1903_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_16_0_load_1 <= state_16_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_16_0_load_1 <= xor_ln127_28_fu_1903_p2;
            else 
                ap_sig_allocacmp_state_16_0_load_1 <= state_16_0_fu_260;
            end if;
        else 
            ap_sig_allocacmp_state_16_0_load_1 <= state_16_0_fu_260;
        end if; 
    end process;


    ap_sig_allocacmp_state_17_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_17_read, ap_block_pp0_stage0, ap_loop_init, state_17_0_fu_280, xor_ln127_30_fu_1921_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_17_0_load_1 <= state_17_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_17_0_load_1 <= xor_ln127_30_fu_1921_p2;
            else 
                ap_sig_allocacmp_state_17_0_load_1 <= state_17_0_fu_280;
            end if;
        else 
            ap_sig_allocacmp_state_17_0_load_1 <= state_17_0_fu_280;
        end if; 
    end process;


    ap_sig_allocacmp_state_18_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_18_read, ap_block_pp0_stage0, ap_loop_init, state_18_0_fu_300, xor_ln127_32_fu_1939_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_18_0_load_1 <= state_18_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_18_0_load_1 <= xor_ln127_32_fu_1939_p2;
            else 
                ap_sig_allocacmp_state_18_0_load_1 <= state_18_0_fu_300;
            end if;
        else 
            ap_sig_allocacmp_state_18_0_load_1 <= state_18_0_fu_300;
        end if; 
    end process;


    ap_sig_allocacmp_state_19_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_19_read, ap_block_pp0_stage0, ap_loop_init, state_19_0_fu_320, xor_ln127_34_fu_1957_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_19_0_load_1 <= state_19_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_19_0_load_1 <= xor_ln127_34_fu_1957_p2;
            else 
                ap_sig_allocacmp_state_19_0_load_1 <= state_19_0_fu_320;
            end if;
        else 
            ap_sig_allocacmp_state_19_0_load_1 <= state_19_0_fu_320;
        end if; 
    end process;


    ap_sig_allocacmp_state_1_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_1_read, ap_block_pp0_stage0, ap_loop_init, state_1_0_fu_248, xor_ln127_1_fu_1663_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_1_0_load_1 <= state_1_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_1_0_load_1 <= xor_ln127_1_fu_1663_p2;
            else 
                ap_sig_allocacmp_state_1_0_load_1 <= state_1_0_fu_248;
            end if;
        else 
            ap_sig_allocacmp_state_1_0_load_1 <= state_1_0_fu_248;
        end if; 
    end process;


    ap_sig_allocacmp_state_20_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_20_read, ap_block_pp0_stage0, ap_loop_init, state_20_0_fu_244, xor_ln127_36_fu_1975_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_20_0_load_1 <= state_20_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_20_0_load_1 <= xor_ln127_36_fu_1975_p2;
            else 
                ap_sig_allocacmp_state_20_0_load_1 <= state_20_0_fu_244;
            end if;
        else 
            ap_sig_allocacmp_state_20_0_load_1 <= state_20_0_fu_244;
        end if; 
    end process;


    ap_sig_allocacmp_state_21_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_21_read, ap_block_pp0_stage0, ap_loop_init, state_21_0_fu_264, xor_ln127_38_fu_1993_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_21_0_load_1 <= state_21_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_21_0_load_1 <= xor_ln127_38_fu_1993_p2;
            else 
                ap_sig_allocacmp_state_21_0_load_1 <= state_21_0_fu_264;
            end if;
        else 
            ap_sig_allocacmp_state_21_0_load_1 <= state_21_0_fu_264;
        end if; 
    end process;


    ap_sig_allocacmp_state_22_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_22_read, ap_block_pp0_stage0, ap_loop_init, state_22_0_fu_284, xor_ln127_40_fu_2011_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_22_0_load_1 <= state_22_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_22_0_load_1 <= xor_ln127_40_fu_2011_p2;
            else 
                ap_sig_allocacmp_state_22_0_load_1 <= state_22_0_fu_284;
            end if;
        else 
            ap_sig_allocacmp_state_22_0_load_1 <= state_22_0_fu_284;
        end if; 
    end process;


    ap_sig_allocacmp_state_2325_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_2325_read, ap_block_pp0_stage0, ap_loop_init, state_2325_0_fu_304, xor_ln127_42_fu_2029_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_2325_0_load_1 <= state_2325_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_2325_0_load_1 <= xor_ln127_42_fu_2029_p2;
            else 
                ap_sig_allocacmp_state_2325_0_load_1 <= state_2325_0_fu_304;
            end if;
        else 
            ap_sig_allocacmp_state_2325_0_load_1 <= state_2325_0_fu_304;
        end if; 
    end process;


    ap_sig_allocacmp_state_24_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_24_read, ap_block_pp0_stage0, ap_loop_init, state_24_0_fu_324, xor_ln127_44_fu_2047_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_24_0_load_1 <= state_24_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_24_0_load_1 <= xor_ln127_44_fu_2047_p2;
            else 
                ap_sig_allocacmp_state_24_0_load_1 <= state_24_0_fu_324;
            end if;
        else 
            ap_sig_allocacmp_state_24_0_load_1 <= state_24_0_fu_324;
        end if; 
    end process;


    ap_sig_allocacmp_state_2_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_2_read, ap_block_pp0_stage0, ap_loop_init, state_2_0_fu_268, xor_ln127_3_fu_1681_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_2_0_load_1 <= state_2_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_2_0_load_1 <= xor_ln127_3_fu_1681_p2;
            else 
                ap_sig_allocacmp_state_2_0_load_1 <= state_2_0_fu_268;
            end if;
        else 
            ap_sig_allocacmp_state_2_0_load_1 <= state_2_0_fu_268;
        end if; 
    end process;


    ap_sig_allocacmp_state_3_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_3_read, ap_block_pp0_stage0, ap_loop_init, state_3_0_fu_288, xor_ln127_4_fu_1687_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_3_0_load_1 <= state_3_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_3_0_load_1 <= xor_ln127_4_fu_1687_p2;
            else 
                ap_sig_allocacmp_state_3_0_load_1 <= state_3_0_fu_288;
            end if;
        else 
            ap_sig_allocacmp_state_3_0_load_1 <= state_3_0_fu_288;
        end if; 
    end process;


    ap_sig_allocacmp_state_4_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_4_read, ap_block_pp0_stage0, ap_loop_init, state_4_0_fu_308, or_ln22_27_fu_1637_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_4_0_load_1 <= state_4_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_4_0_load_1 <= or_ln22_27_fu_1637_p3;
            else 
                ap_sig_allocacmp_state_4_0_load_1 <= state_4_0_fu_308;
            end if;
        else 
            ap_sig_allocacmp_state_4_0_load_1 <= state_4_0_fu_308;
        end if; 
    end process;


    ap_sig_allocacmp_state_5_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_5_read, ap_block_pp0_stage0, ap_loop_init, state_5_0_fu_232, xor_ln127_6_fu_1705_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_5_0_load_1 <= state_5_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_5_0_load_1 <= xor_ln127_6_fu_1705_p2;
            else 
                ap_sig_allocacmp_state_5_0_load_1 <= state_5_0_fu_232;
            end if;
        else 
            ap_sig_allocacmp_state_5_0_load_1 <= state_5_0_fu_232;
        end if; 
    end process;


    ap_sig_allocacmp_state_6_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_6_read, ap_block_pp0_stage0, ap_loop_init, state_6_0_fu_252, xor_ln127_8_fu_1723_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_6_0_load_1 <= state_6_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_6_0_load_1 <= xor_ln127_8_fu_1723_p2;
            else 
                ap_sig_allocacmp_state_6_0_load_1 <= state_6_0_fu_252;
            end if;
        else 
            ap_sig_allocacmp_state_6_0_load_1 <= state_6_0_fu_252;
        end if; 
    end process;


    ap_sig_allocacmp_state_7_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_7_read, ap_block_pp0_stage0, ap_loop_init, state_7_0_fu_272, xor_ln127_10_fu_1741_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_7_0_load_1 <= state_7_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_7_0_load_1 <= xor_ln127_10_fu_1741_p2;
            else 
                ap_sig_allocacmp_state_7_0_load_1 <= state_7_0_fu_272;
            end if;
        else 
            ap_sig_allocacmp_state_7_0_load_1 <= state_7_0_fu_272;
        end if; 
    end process;


    ap_sig_allocacmp_state_8_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_8_read, ap_block_pp0_stage0, ap_loop_init, state_8_0_fu_292, xor_ln127_12_fu_1759_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_8_0_load_1 <= state_8_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_8_0_load_1 <= xor_ln127_12_fu_1759_p2;
            else 
                ap_sig_allocacmp_state_8_0_load_1 <= state_8_0_fu_292;
            end if;
        else 
            ap_sig_allocacmp_state_8_0_load_1 <= state_8_0_fu_292;
        end if; 
    end process;


    ap_sig_allocacmp_state_9_0_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_9_read, ap_block_pp0_stage0, ap_loop_init, state_9_0_fu_312, xor_ln127_14_fu_1777_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_9_0_load_1 <= state_9_read;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_state_9_0_load_1 <= xor_ln127_14_fu_1777_p2;
            else 
                ap_sig_allocacmp_state_9_0_load_1 <= state_9_0_fu_312;
            end if;
        else 
            ap_sig_allocacmp_state_9_0_load_1 <= state_9_0_fu_312;
        end if; 
    end process;

    icmp_ln149_fu_628_p2 <= "1" when (ap_sig_allocacmp_round_1 = ap_const_lv5_18) else "0";
    lshr_ln22_10_fu_1363_p4 <= x_16_fu_1041_p2(63 downto 21);
    lshr_ln22_11_fu_1385_p4 <= x_17_fu_1047_p2(63 downto 39);
    lshr_ln22_12_fu_1407_p4 <= x_18_fu_1053_p2(63 downto 25);
    lshr_ln22_13_fu_1429_p4 <= x_19_fu_1059_p2(63 downto 23);
    lshr_ln22_14_fu_1451_p4 <= x_20_fu_1065_p2(63 downto 19);
    lshr_ln22_15_fu_1473_p4 <= x_21_fu_1071_p2(63 downto 49);
    lshr_ln22_16_fu_1495_p4 <= x_22_fu_1077_p2(63 downto 43);
    lshr_ln22_17_fu_1517_p4 <= x_23_fu_1083_p2(63 downto 56);
    lshr_ln22_18_fu_1539_p4 <= x_24_fu_1089_p2(63 downto 46);
    lshr_ln22_19_fu_1561_p4 <= x_25_fu_1095_p2(63 downto 62);
    lshr_ln22_1_fu_1253_p4 <= x_11_fu_1011_p2(63 downto 58);
    lshr_ln22_20_fu_1583_p4 <= x_26_fu_1101_p2(63 downto 3);
    lshr_ln22_21_fu_1605_p4 <= x_27_fu_1107_p2(63 downto 8);
    lshr_ln22_22_fu_1627_p4 <= x_28_fu_1113_p2(63 downto 50);
    lshr_ln22_2_fu_1275_p4 <= x_12_fu_1017_p2(63 downto 9);
    lshr_ln22_3_fu_1297_p4 <= x_13_fu_1023_p2(63 downto 44);
    lshr_ln22_4_fu_1319_p4 <= x_14_fu_1029_p2(63 downto 61);
    lshr_ln22_5_fu_1341_p4 <= x_15_fu_1035_p2(63 downto 54);
    lshr_ln22_6_fu_1143_p4 <= x_6_fu_981_p2(63 downto 2);
    lshr_ln22_7_fu_1165_p4 <= x_7_fu_987_p2(63 downto 36);
    lshr_ln22_8_fu_1187_p4 <= x_8_fu_993_p2(63 downto 37);
    lshr_ln22_9_fu_1209_p4 <= x_9_fu_999_p2(63 downto 28);
    lshr_ln22_s_fu_1231_p4 <= x_10_fu_1005_p2(63 downto 20);
    or_ln127_fu_1651_p2 <= (xor_ln127_fu_1645_p2 or or_ln22_s_fu_1241_p3);
    or_ln22_10_fu_1263_p3 <= (trunc_ln22_11_fu_1249_p1 & lshr_ln22_1_fu_1253_p4);
    or_ln22_11_fu_1285_p3 <= (trunc_ln22_12_fu_1271_p1 & lshr_ln22_2_fu_1275_p4);
    or_ln22_12_fu_1307_p3 <= (trunc_ln22_13_fu_1293_p1 & lshr_ln22_3_fu_1297_p4);
    or_ln22_13_fu_1329_p3 <= (trunc_ln22_14_fu_1315_p1 & lshr_ln22_4_fu_1319_p4);
    or_ln22_14_fu_1351_p3 <= (trunc_ln22_15_fu_1337_p1 & lshr_ln22_5_fu_1341_p4);
    or_ln22_15_fu_1373_p3 <= (trunc_ln22_16_fu_1359_p1 & lshr_ln22_10_fu_1363_p4);
    or_ln22_16_fu_1395_p3 <= (trunc_ln22_17_fu_1381_p1 & lshr_ln22_11_fu_1385_p4);
    or_ln22_17_fu_1417_p3 <= (trunc_ln22_18_fu_1403_p1 & lshr_ln22_12_fu_1407_p4);
    or_ln22_18_fu_1439_p3 <= (trunc_ln22_19_fu_1425_p1 & lshr_ln22_13_fu_1429_p4);
    or_ln22_19_fu_1461_p3 <= (trunc_ln22_20_fu_1447_p1 & lshr_ln22_14_fu_1451_p4);
    or_ln22_1_fu_883_p3 <= (trunc_ln22_1_fu_871_p1 & tmp_3_fu_875_p3);
    or_ln22_20_fu_1483_p3 <= (trunc_ln22_21_fu_1469_p1 & lshr_ln22_15_fu_1473_p4);
    or_ln22_21_fu_1505_p3 <= (trunc_ln22_22_fu_1491_p1 & lshr_ln22_16_fu_1495_p4);
    or_ln22_22_fu_1527_p3 <= (trunc_ln22_23_fu_1513_p1 & lshr_ln22_17_fu_1517_p4);
    or_ln22_23_fu_1549_p3 <= (trunc_ln22_24_fu_1535_p1 & lshr_ln22_18_fu_1539_p4);
    or_ln22_24_fu_1571_p3 <= (trunc_ln22_25_fu_1557_p1 & lshr_ln22_19_fu_1561_p4);
    or_ln22_25_fu_1593_p3 <= (trunc_ln22_26_fu_1579_p1 & lshr_ln22_20_fu_1583_p4);
    or_ln22_26_fu_1615_p3 <= (trunc_ln22_27_fu_1601_p1 & lshr_ln22_21_fu_1605_p4);
    or_ln22_27_fu_1637_p3 <= (trunc_ln22_28_fu_1623_p1 & lshr_ln22_22_fu_1627_p4);
    or_ln22_2_fu_909_p3 <= (trunc_ln22_2_fu_897_p1 & tmp_4_fu_901_p3);
    or_ln22_3_fu_935_p3 <= (trunc_ln22_3_fu_923_p1 & tmp_5_fu_927_p3);
    or_ln22_4_fu_961_p3 <= (trunc_ln22_4_fu_949_p1 & tmp_6_fu_953_p3);
    or_ln22_5_fu_1131_p3 <= (trunc_ln22_5_fu_1119_p1 & tmp_7_fu_1123_p3);
    or_ln22_6_fu_1153_p3 <= (trunc_ln22_6_fu_1139_p1 & lshr_ln22_6_fu_1143_p4);
    or_ln22_7_fu_1175_p3 <= (trunc_ln22_7_fu_1161_p1 & lshr_ln22_7_fu_1165_p4);
    or_ln22_8_fu_1197_p3 <= (trunc_ln22_8_fu_1183_p1 & lshr_ln22_8_fu_1187_p4);
    or_ln22_9_fu_1219_p3 <= (trunc_ln22_9_fu_1205_p1 & lshr_ln22_9_fu_1209_p4);
    or_ln22_s_fu_1241_p3 <= (trunc_ln22_10_fu_1227_p1 & lshr_ln22_s_fu_1231_p4);
    or_ln_fu_857_p3 <= (trunc_ln22_fu_845_p1 & tmp_fu_849_p3);
    tmp_3_fu_875_p3 <= x_1_fu_791_p2(63 downto 63);
    tmp_4_fu_901_p3 <= x_2_fu_815_p2(63 downto 63);
    tmp_5_fu_927_p3 <= x_3_fu_839_p2(63 downto 63);
    tmp_6_fu_953_p3 <= x_4_fu_743_p2(63 downto 63);
    tmp_7_fu_1123_p3 <= x_5_fu_975_p2(63 downto 63);
    tmp_fu_849_p3 <= x_fu_767_p2(63 downto 63);
    trunc_ln22_10_fu_1227_p1 <= x_10_fu_1005_p2(20 - 1 downto 0);
    trunc_ln22_11_fu_1249_p1 <= x_11_fu_1011_p2(58 - 1 downto 0);
    trunc_ln22_12_fu_1271_p1 <= x_12_fu_1017_p2(9 - 1 downto 0);
    trunc_ln22_13_fu_1293_p1 <= x_13_fu_1023_p2(44 - 1 downto 0);
    trunc_ln22_14_fu_1315_p1 <= x_14_fu_1029_p2(61 - 1 downto 0);
    trunc_ln22_15_fu_1337_p1 <= x_15_fu_1035_p2(54 - 1 downto 0);
    trunc_ln22_16_fu_1359_p1 <= x_16_fu_1041_p2(21 - 1 downto 0);
    trunc_ln22_17_fu_1381_p1 <= x_17_fu_1047_p2(39 - 1 downto 0);
    trunc_ln22_18_fu_1403_p1 <= x_18_fu_1053_p2(25 - 1 downto 0);
    trunc_ln22_19_fu_1425_p1 <= x_19_fu_1059_p2(23 - 1 downto 0);
    trunc_ln22_1_fu_871_p1 <= x_1_fu_791_p2(63 - 1 downto 0);
    trunc_ln22_20_fu_1447_p1 <= x_20_fu_1065_p2(19 - 1 downto 0);
    trunc_ln22_21_fu_1469_p1 <= x_21_fu_1071_p2(49 - 1 downto 0);
    trunc_ln22_22_fu_1491_p1 <= x_22_fu_1077_p2(43 - 1 downto 0);
    trunc_ln22_23_fu_1513_p1 <= x_23_fu_1083_p2(56 - 1 downto 0);
    trunc_ln22_24_fu_1535_p1 <= x_24_fu_1089_p2(46 - 1 downto 0);
    trunc_ln22_25_fu_1557_p1 <= x_25_fu_1095_p2(62 - 1 downto 0);
    trunc_ln22_26_fu_1579_p1 <= x_26_fu_1101_p2(3 - 1 downto 0);
    trunc_ln22_27_fu_1601_p1 <= x_27_fu_1107_p2(8 - 1 downto 0);
    trunc_ln22_28_fu_1623_p1 <= x_28_fu_1113_p2(50 - 1 downto 0);
    trunc_ln22_2_fu_897_p1 <= x_2_fu_815_p2(63 - 1 downto 0);
    trunc_ln22_3_fu_923_p1 <= x_3_fu_839_p2(63 - 1 downto 0);
    trunc_ln22_4_fu_949_p1 <= x_4_fu_743_p2(63 - 1 downto 0);
    trunc_ln22_5_fu_1119_p1 <= x_5_fu_975_p2(63 - 1 downto 0);
    trunc_ln22_6_fu_1139_p1 <= x_6_fu_981_p2(2 - 1 downto 0);
    trunc_ln22_7_fu_1161_p1 <= x_7_fu_987_p2(36 - 1 downto 0);
    trunc_ln22_8_fu_1183_p1 <= x_8_fu_993_p2(37 - 1 downto 0);
    trunc_ln22_9_fu_1205_p1 <= x_9_fu_999_p2(28 - 1 downto 0);
    trunc_ln22_fu_845_p1 <= x_fu_767_p2(63 - 1 downto 0);
    x_10_fu_1005_p2 <= (xor_ln57_1_fu_891_p2 xor state_6_0_fu_252);
    x_11_fu_1011_p2 <= (xor_ln57_2_fu_917_p2 xor state_7_0_fu_272);
    x_12_fu_1017_p2 <= (xor_ln57_3_fu_943_p2 xor state_8_0_fu_292);
    x_13_fu_1023_p2 <= (xor_ln57_4_fu_969_p2 xor state_9_0_fu_312);
    x_14_fu_1029_p2 <= (xor_ln57_fu_865_p2 xor state_10_0_fu_236);
    x_15_fu_1035_p2 <= (xor_ln57_1_fu_891_p2 xor state_11_0_fu_256);
    x_16_fu_1041_p2 <= (xor_ln57_2_fu_917_p2 xor state_1213_0_fu_276);
    x_17_fu_1047_p2 <= (xor_ln57_3_fu_943_p2 xor state_13_0_fu_296);
    x_18_fu_1053_p2 <= (xor_ln57_4_fu_969_p2 xor state_14_0_fu_316);
    x_19_fu_1059_p2 <= (xor_ln57_fu_865_p2 xor state_1549_0_fu_240);
    x_1_fu_791_p2 <= (xor_ln50_8_fu_773_p2 xor xor_ln50_10_fu_785_p2);
    x_20_fu_1065_p2 <= (xor_ln57_1_fu_891_p2 xor state_16_0_fu_260);
    x_21_fu_1071_p2 <= (xor_ln57_2_fu_917_p2 xor state_17_0_fu_280);
    x_22_fu_1077_p2 <= (xor_ln57_3_fu_943_p2 xor state_18_0_fu_300);
    x_23_fu_1083_p2 <= (xor_ln57_4_fu_969_p2 xor state_19_0_fu_320);
    x_24_fu_1089_p2 <= (xor_ln57_fu_865_p2 xor state_20_0_fu_244);
    x_25_fu_1095_p2 <= (xor_ln57_1_fu_891_p2 xor state_21_0_fu_264);
    x_26_fu_1101_p2 <= (xor_ln57_2_fu_917_p2 xor state_22_0_fu_284);
    x_27_fu_1107_p2 <= (xor_ln57_3_fu_943_p2 xor state_2325_0_fu_304);
    x_28_fu_1113_p2 <= (xor_ln57_4_fu_969_p2 xor state_24_0_fu_324);
    x_2_fu_815_p2 <= (xor_ln50_14_fu_809_p2 xor xor_ln50_12_fu_797_p2);
    x_3_fu_839_p2 <= (xor_ln50_18_fu_833_p2 xor xor_ln50_16_fu_821_p2);
    x_4_fu_743_p2 <= (xor_ln50_fu_725_p2 xor xor_ln50_2_fu_737_p2);
    x_5_fu_975_p2 <= (xor_ln57_1_fu_891_p2 xor state_1_0_fu_248);
    x_6_fu_981_p2 <= (xor_ln57_2_fu_917_p2 xor state_2_0_fu_268);
    x_7_fu_987_p2 <= (xor_ln57_3_fu_943_p2 xor state_3_0_fu_288);
    x_8_fu_993_p2 <= (xor_ln57_4_fu_969_p2 xor state_4_0_fu_308);
    x_9_fu_999_p2 <= (xor_ln57_fu_865_p2 xor state_5_0_fu_232);
    x_fu_767_p2 <= (xor_ln50_6_fu_761_p2 xor xor_ln50_4_fu_749_p2);
    xor_ln127_10_fu_1741_p2 <= (or_ln22_13_fu_1329_p3 xor and_ln127_4_fu_1735_p2);
    xor_ln127_11_fu_1747_p2 <= (or_ln22_25_fu_1593_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_12_fu_1759_p2 <= (or_ln22_19_fu_1461_p3 xor and_ln127_5_fu_1753_p2);
    xor_ln127_13_fu_1765_p2 <= (or_ln22_7_fu_1175_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_14_fu_1777_p2 <= (or_ln22_25_fu_1593_p3 xor and_ln127_6_fu_1771_p2);
    xor_ln127_15_fu_1783_p2 <= (or_ln22_10_fu_1263_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_16_fu_1795_p2 <= (or_ln22_5_fu_1131_p3 xor and_ln127_7_fu_1789_p2);
    xor_ln127_17_fu_1801_p2 <= (or_ln22_16_fu_1395_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_18_fu_1813_p2 <= (or_ln22_10_fu_1263_p3 xor and_ln127_8_fu_1807_p2);
    xor_ln127_19_fu_1819_p2 <= (or_ln22_22_fu_1527_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_1_fu_1663_p2 <= (or_ln22_s_fu_1241_p3 xor and_ln127_fu_1657_p2);
    xor_ln127_20_fu_1831_p2 <= (or_ln22_16_fu_1395_p3 xor and_ln127_9_fu_1825_p2);
    xor_ln127_21_fu_1837_p2 <= (or_ln22_23_fu_1549_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_22_fu_1849_p2 <= (or_ln22_22_fu_1527_p3 xor and_ln127_10_fu_1843_p2);
    xor_ln127_23_fu_1855_p2 <= (or_ln22_5_fu_1131_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_24_fu_1867_p2 <= (or_ln22_23_fu_1549_p3 xor and_ln127_11_fu_1861_p2);
    xor_ln127_25_fu_1873_p2 <= (or_ln22_9_fu_1219_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_26_fu_1885_p2 <= (or_ln22_8_fu_1197_p3 xor and_ln127_12_fu_1879_p2);
    xor_ln127_27_fu_1891_p2 <= (or_ln22_14_fu_1351_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_28_fu_1903_p2 <= (or_ln22_9_fu_1219_p3 xor and_ln127_13_fu_1897_p2);
    xor_ln127_29_fu_1909_p2 <= (or_ln22_20_fu_1483_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_2_fu_1669_p2 <= (or_ln22_21_fu_1505_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_30_fu_1921_p2 <= (or_ln22_14_fu_1351_p3 xor and_ln127_14_fu_1915_p2);
    xor_ln127_31_fu_1927_p2 <= (or_ln22_26_fu_1615_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_32_fu_1939_p2 <= (or_ln22_20_fu_1483_p3 xor and_ln127_15_fu_1933_p2);
    xor_ln127_33_fu_1945_p2 <= (or_ln22_8_fu_1197_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_34_fu_1957_p2 <= (or_ln22_26_fu_1615_p3 xor and_ln127_16_fu_1951_p2);
    xor_ln127_35_fu_1963_p2 <= (or_ln22_11_fu_1285_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_36_fu_1975_p2 <= (or_ln22_6_fu_1153_p3 xor and_ln127_17_fu_1969_p2);
    xor_ln127_37_fu_1981_p2 <= (or_ln22_17_fu_1417_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_38_fu_1993_p2 <= (or_ln22_11_fu_1285_p3 xor and_ln127_18_fu_1987_p2);
    xor_ln127_39_fu_1999_p2 <= (or_ln22_18_fu_1439_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_3_fu_1681_p2 <= (or_ln22_15_fu_1373_p3 xor and_ln127_1_fu_1675_p2);
    xor_ln127_40_fu_2011_p2 <= (or_ln22_17_fu_1417_p3 xor and_ln127_19_fu_2005_p2);
    xor_ln127_41_fu_2017_p2 <= (or_ln22_24_fu_1571_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_42_fu_2029_p2 <= (or_ln22_18_fu_1439_p3 xor and_ln127_20_fu_2023_p2);
    xor_ln127_43_fu_2035_p2 <= (or_ln22_6_fu_1153_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_44_fu_2047_p2 <= (or_ln22_24_fu_1571_p3 xor and_ln127_21_fu_2041_p2);
    xor_ln127_4_fu_1687_p2 <= (xor_ln127_2_fu_1669_p2 xor or_ln22_27_fu_1637_p3);
    xor_ln127_5_fu_1693_p2 <= (or_ln22_12_fu_1307_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_6_fu_1705_p2 <= (or_ln22_7_fu_1175_p3 xor and_ln127_2_fu_1699_p2);
    xor_ln127_7_fu_1711_p2 <= (or_ln22_13_fu_1329_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_8_fu_1723_p2 <= (or_ln22_12_fu_1307_p3 xor and_ln127_3_fu_1717_p2);
    xor_ln127_9_fu_1729_p2 <= (or_ln22_19_fu_1461_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln127_fu_1645_p2 <= (or_ln22_15_fu_1373_p3 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln137_fu_2053_p2 <= (or_ln127_fu_1651_p2 xor RC_TABLE_q0);
    xor_ln50_10_fu_785_p2 <= (xor_ln50_9_fu_779_p2 xor state_22_0_fu_284);
    xor_ln50_12_fu_797_p2 <= (state_8_0_fu_292 xor state_13_0_fu_296);
    xor_ln50_13_fu_803_p2 <= (state_3_0_fu_288 xor state_18_0_fu_300);
    xor_ln50_14_fu_809_p2 <= (xor_ln50_13_fu_803_p2 xor state_2325_0_fu_304);
    xor_ln50_16_fu_821_p2 <= (state_9_0_fu_312 xor state_14_0_fu_316);
    xor_ln50_17_fu_827_p2 <= (state_4_0_fu_308 xor state_19_0_fu_320);
    xor_ln50_18_fu_833_p2 <= (xor_ln50_17_fu_827_p2 xor state_24_0_fu_324);
    xor_ln50_1_fu_731_p2 <= (state_1549_0_fu_240 xor state_0_0_fu_228);
    xor_ln50_2_fu_737_p2 <= (xor_ln50_1_fu_731_p2 xor state_20_0_fu_244);
    xor_ln50_4_fu_749_p2 <= (state_6_0_fu_252 xor state_11_0_fu_256);
    xor_ln50_5_fu_755_p2 <= (state_1_0_fu_248 xor state_16_0_fu_260);
    xor_ln50_6_fu_761_p2 <= (xor_ln50_5_fu_755_p2 xor state_21_0_fu_264);
    xor_ln50_8_fu_773_p2 <= (state_7_0_fu_272 xor state_1213_0_fu_276);
    xor_ln50_9_fu_779_p2 <= (state_2_0_fu_268 xor state_17_0_fu_280);
    xor_ln50_fu_725_p2 <= (state_5_0_fu_232 xor state_10_0_fu_236);
    xor_ln57_1_fu_891_p2 <= (x_4_fu_743_p2 xor or_ln22_1_fu_883_p3);
    xor_ln57_2_fu_917_p2 <= (x_fu_767_p2 xor or_ln22_2_fu_909_p3);
    xor_ln57_3_fu_943_p2 <= (x_1_fu_791_p2 xor or_ln22_3_fu_935_p3);
    xor_ln57_4_fu_969_p2 <= (x_2_fu_815_p2 xor or_ln22_4_fu_961_p3);
    xor_ln57_fu_865_p2 <= (x_3_fu_839_p2 xor or_ln_fu_857_p3);
    zext_ln149_fu_640_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_round_1),64));
end behav;
