

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "4", "7", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21"],
		"CDFG" : "keccak_top",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "78", "EstimateLatencyMax" : "64578",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_stream_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_keccak_top_Pipeline_ABSORB_BLOCK_fu_3850", "Port" : "input_stream_V_data_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "input_stream_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_keccak_top_Pipeline_ABSORB_BLOCK_fu_3850", "Port" : "input_stream_V_keep_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "input_stream_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_keccak_top_Pipeline_ABSORB_BLOCK_fu_3850", "Port" : "input_stream_V_strb_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "input_stream_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_keccak_top_Pipeline_ABSORB_BLOCK_fu_3850", "Port" : "input_stream_V_last_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "output_stream_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "output_stream",
				"SubConnect" : [
					{"ID" : "7", "SubInstance" : "grp_keccak_top_Pipeline_SQUEEZE_BLOCK_fu_3947", "Port" : "output_stream_V_data_V", "Inst_start_state" : "43", "Inst_end_state" : "44"}]},
			{"Name" : "output_stream_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "output_stream",
				"SubConnect" : [
					{"ID" : "7", "SubInstance" : "grp_keccak_top_Pipeline_SQUEEZE_BLOCK_fu_3947", "Port" : "output_stream_V_keep_V", "Inst_start_state" : "43", "Inst_end_state" : "44"}]},
			{"Name" : "output_stream_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "output_stream",
				"SubConnect" : [
					{"ID" : "7", "SubInstance" : "grp_keccak_top_Pipeline_SQUEEZE_BLOCK_fu_3947", "Port" : "output_stream_V_strb_V", "Inst_start_state" : "43", "Inst_end_state" : "44"}]},
			{"Name" : "output_stream_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "output_stream",
				"SubConnect" : [
					{"ID" : "7", "SubInstance" : "grp_keccak_top_Pipeline_SQUEEZE_BLOCK_fu_3947", "Port" : "output_stream_V_last_V", "Inst_start_state" : "43", "Inst_end_state" : "44"}]},
			{"Name" : "rate_bytes", "Type" : "None", "Direction" : "I"},
			{"Name" : "delimiter", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_len", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_len", "Type" : "None", "Direction" : "I"},
			{"Name" : "RC_TABLE", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "grp_keccak_f1600_fu_3891", "Port" : "RC_TABLE", "Inst_start_state" : "45", "Inst_end_state" : "46"}]}],
		"Loop" : [
			{"Name" : "ABSORB_LOOP", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "47", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state5"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state6"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "SQUEEZE_LOOP", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "47", "FirstState" : "ap_ST_fsm_state43", "LastState" : ["ap_ST_fsm_state46"], "QuitState" : ["ap_ST_fsm_state43"], "PreState" : ["ap_ST_fsm_state42"], "PostState" : ["ap_ST_fsm_state47"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_keccak_top_Pipeline_ABSORB_BLOCK_fu_3850", "Parent" : "0", "Child" : ["2", "3"],
		"CDFG" : "keccak_top_Pipeline_ABSORB_BLOCK",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "34",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "1",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "message_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "trunc_ln1", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_24", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_23", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_22", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_21", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_20", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_19", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_18", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_17", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_16", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_15", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_14", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_13", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_12", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_11", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_10", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_9", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_8", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_7", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_6", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_5", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_4", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "input_stream_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream",
				"BlockSignal" : [
					{"Name" : "input_stream_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "input_stream_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream"},
			{"Name" : "input_stream_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream"},
			{"Name" : "input_stream_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream"},
			{"Name" : "message_done_1_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "ABSORB_BLOCK", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_keccak_top_Pipeline_ABSORB_BLOCK_fu_3850.sparsemux_51_5_64_1_1_U1", "Parent" : "1"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_keccak_top_Pipeline_ABSORB_BLOCK_fu_3850.flow_control_loop_pipe_sequential_init_U", "Parent" : "1"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_keccak_f1600_fu_3891", "Parent" : "0", "Child" : ["5", "6"],
		"CDFG" : "keccak_f1600",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "26", "EstimateLatencyMax" : "26",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "state_0_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_1_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_2_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_3_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_4_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_5_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_6_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_7_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_8_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_9_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_10_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_11_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_1213_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_13_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_14_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_15_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_16_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_17_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_18_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_19_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_20_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_21_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_22_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_2325_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_24_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "RC_TABLE", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "KECCAK_ROUNDS_LOOP", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_keccak_f1600_fu_3891.RC_TABLE_U", "Parent" : "4"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_keccak_f1600_fu_3891.flow_control_loop_pipe_sequential_init_U", "Parent" : "4"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_keccak_top_Pipeline_SQUEEZE_BLOCK_fu_3947", "Parent" : "0", "Child" : ["8", "9"],
		"CDFG" : "keccak_top_Pipeline_SQUEEZE_BLOCK",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "34",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "output_remaining", "Type" : "None", "Direction" : "I"},
			{"Name" : "trunc_ln6", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_1_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_2_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_3_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_4_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_5_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_6_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_7_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_8_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_9_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_10_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_11_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_12_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_13_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_14_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_15_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_16_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_17_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_18_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_19_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_20_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_21_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_22_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_23_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "state_24_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_stream_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "output_stream",
				"BlockSignal" : [
					{"Name" : "output_stream_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "output_stream_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "output_stream"},
			{"Name" : "output_stream_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "output_stream"},
			{"Name" : "output_stream_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "output_stream"},
			{"Name" : "output_remaining_1_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "SQUEEZE_BLOCK", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_keccak_top_Pipeline_SQUEEZE_BLOCK_fu_3947.sparsemux_51_5_64_1_1_U61", "Parent" : "7"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_keccak_top_Pipeline_SQUEEZE_BLOCK_fu_3947.flow_control_loop_pipe_sequential_init_U", "Parent" : "7"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.urem_32ns_8ns_32_36_seq_1_U94", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_51_5_64_1_1_U95", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_51_5_64_1_1_U96", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_data_V_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_keep_V_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_strb_V_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_last_V_U", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_data_V_U", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_keep_V_U", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_strb_V_U", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_last_V_U", "Parent" : "0"}]}
