# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jakub/projects/rim-projekt/keccak/keccak.srcs/sources_1/ip/keccak_top_0/keccak_top_0.xci
# IP: The module: 'keccak_top_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jakub/projects/rim-projekt/keccak/keccak.gen/sources_1/ip/keccak_top_0/constraints/keccak_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'keccak_top_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/jakub/projects/rim-projekt/keccak/keccak.srcs/sources_1/ip/keccak_top_0/keccak_top_0.xci
# IP: The module: 'keccak_top_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jakub/projects/rim-projekt/keccak/keccak.gen/sources_1/ip/keccak_top_0/constraints/keccak_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'keccak_top_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
