-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity keccak_top_keccak_top_Pipeline_ABSORB_BLOCK is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_stream_TVALID : IN STD_LOGIC;
    message_done : IN STD_LOGIC_VECTOR (0 downto 0);
    trunc_ln1 : IN STD_LOGIC_VECTOR (5 downto 0);
    state_24_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_24_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_24_o_ap_vld : OUT STD_LOGIC;
    state_23_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_23_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_23_o_ap_vld : OUT STD_LOGIC;
    state_22_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_22_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_22_o_ap_vld : OUT STD_LOGIC;
    state_21_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_21_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_21_o_ap_vld : OUT STD_LOGIC;
    state_20_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_20_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_20_o_ap_vld : OUT STD_LOGIC;
    state_19_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_19_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_19_o_ap_vld : OUT STD_LOGIC;
    state_18_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_18_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_18_o_ap_vld : OUT STD_LOGIC;
    state_17_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_17_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_17_o_ap_vld : OUT STD_LOGIC;
    state_16_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_16_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_16_o_ap_vld : OUT STD_LOGIC;
    state_15_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_15_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_15_o_ap_vld : OUT STD_LOGIC;
    state_14_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_14_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_14_o_ap_vld : OUT STD_LOGIC;
    state_13_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_13_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_13_o_ap_vld : OUT STD_LOGIC;
    state_12_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_12_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_12_o_ap_vld : OUT STD_LOGIC;
    state_11_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_11_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_11_o_ap_vld : OUT STD_LOGIC;
    state_10_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_10_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_10_o_ap_vld : OUT STD_LOGIC;
    state_9_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_9_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_9_o_ap_vld : OUT STD_LOGIC;
    state_8_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_8_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_8_o_ap_vld : OUT STD_LOGIC;
    state_7_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_7_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_7_o_ap_vld : OUT STD_LOGIC;
    state_6_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_6_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_6_o_ap_vld : OUT STD_LOGIC;
    state_5_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_5_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_5_o_ap_vld : OUT STD_LOGIC;
    state_4_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_4_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_4_o_ap_vld : OUT STD_LOGIC;
    state_3_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_3_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_3_o_ap_vld : OUT STD_LOGIC;
    state_2_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_2_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_2_o_ap_vld : OUT STD_LOGIC;
    state_1_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_1_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_1_o_ap_vld : OUT STD_LOGIC;
    state_i : IN STD_LOGIC_VECTOR (63 downto 0);
    state_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_o_ap_vld : OUT STD_LOGIC;
    input_stream_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    input_stream_TREADY : OUT STD_LOGIC;
    input_stream_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    input_stream_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    input_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    message_done_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    message_done_1_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of keccak_top_keccak_top_Pipeline_ABSORB_BLOCK is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv5_16 : STD_LOGIC_VECTOR (4 downto 0) := "10110";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_13 : STD_LOGIC_VECTOR (4 downto 0) := "10011";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_B : STD_LOGIC_VECTOR (4 downto 0) := "01011";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal tmp_1_nbreadreq_fu_188_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln300_fu_559_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal input_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal trunc_ln300_fu_571_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln300_reg_815 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_fu_168 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln300_fu_565_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal message_done_1_fu_172 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal message_done_2_fu_782_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal state_25_fu_695_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal tmp_2_fu_588_p51 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_2_fu_588_p53 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_2_fu_588_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p5 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p7 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p9 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p11 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p13 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p15 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p17 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p19 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p21 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p23 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p25 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p27 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p29 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p31 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p33 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p35 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p37 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p39 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p41 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p43 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p45 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p47 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_588_p49 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component keccak_top_sparsemux_51_5_64_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (4 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (4 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (4 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (4 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (4 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (4 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (4 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (4 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (4 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (4 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (4 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (4 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (4 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (4 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (4 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (4 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (4 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (4 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (4 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (4 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (4 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (4 downto 0);
        din21_WIDTH : INTEGER;
        CASE22 : STD_LOGIC_VECTOR (4 downto 0);
        din22_WIDTH : INTEGER;
        CASE23 : STD_LOGIC_VECTOR (4 downto 0);
        din23_WIDTH : INTEGER;
        CASE24 : STD_LOGIC_VECTOR (4 downto 0);
        din24_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        din2 : IN STD_LOGIC_VECTOR (63 downto 0);
        din3 : IN STD_LOGIC_VECTOR (63 downto 0);
        din4 : IN STD_LOGIC_VECTOR (63 downto 0);
        din5 : IN STD_LOGIC_VECTOR (63 downto 0);
        din6 : IN STD_LOGIC_VECTOR (63 downto 0);
        din7 : IN STD_LOGIC_VECTOR (63 downto 0);
        din8 : IN STD_LOGIC_VECTOR (63 downto 0);
        din9 : IN STD_LOGIC_VECTOR (63 downto 0);
        din10 : IN STD_LOGIC_VECTOR (63 downto 0);
        din11 : IN STD_LOGIC_VECTOR (63 downto 0);
        din12 : IN STD_LOGIC_VECTOR (63 downto 0);
        din13 : IN STD_LOGIC_VECTOR (63 downto 0);
        din14 : IN STD_LOGIC_VECTOR (63 downto 0);
        din15 : IN STD_LOGIC_VECTOR (63 downto 0);
        din16 : IN STD_LOGIC_VECTOR (63 downto 0);
        din17 : IN STD_LOGIC_VECTOR (63 downto 0);
        din18 : IN STD_LOGIC_VECTOR (63 downto 0);
        din19 : IN STD_LOGIC_VECTOR (63 downto 0);
        din20 : IN STD_LOGIC_VECTOR (63 downto 0);
        din21 : IN STD_LOGIC_VECTOR (63 downto 0);
        din22 : IN STD_LOGIC_VECTOR (63 downto 0);
        din23 : IN STD_LOGIC_VECTOR (63 downto 0);
        din24 : IN STD_LOGIC_VECTOR (63 downto 0);
        def : IN STD_LOGIC_VECTOR (63 downto 0);
        sel : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component keccak_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_51_5_64_1_1_U1 : component keccak_top_sparsemux_51_5_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00000",
        din0_WIDTH => 64,
        CASE1 => "00001",
        din1_WIDTH => 64,
        CASE2 => "00010",
        din2_WIDTH => 64,
        CASE3 => "00011",
        din3_WIDTH => 64,
        CASE4 => "00100",
        din4_WIDTH => 64,
        CASE5 => "00101",
        din5_WIDTH => 64,
        CASE6 => "00110",
        din6_WIDTH => 64,
        CASE7 => "00111",
        din7_WIDTH => 64,
        CASE8 => "01000",
        din8_WIDTH => 64,
        CASE9 => "01001",
        din9_WIDTH => 64,
        CASE10 => "01010",
        din10_WIDTH => 64,
        CASE11 => "01011",
        din11_WIDTH => 64,
        CASE12 => "01100",
        din12_WIDTH => 64,
        CASE13 => "01101",
        din13_WIDTH => 64,
        CASE14 => "01110",
        din14_WIDTH => 64,
        CASE15 => "01111",
        din15_WIDTH => 64,
        CASE16 => "10000",
        din16_WIDTH => 64,
        CASE17 => "10001",
        din17_WIDTH => 64,
        CASE18 => "10010",
        din18_WIDTH => 64,
        CASE19 => "10011",
        din19_WIDTH => 64,
        CASE20 => "10100",
        din20_WIDTH => 64,
        CASE21 => "10101",
        din21_WIDTH => 64,
        CASE22 => "10110",
        din22_WIDTH => 64,
        CASE23 => "10111",
        din23_WIDTH => 64,
        CASE24 => "11000",
        din24_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 5,
        dout_WIDTH => 64)
    port map (
        din0 => state_i,
        din1 => state_1_i,
        din2 => state_2_i,
        din3 => state_3_i,
        din4 => state_4_i,
        din5 => state_5_i,
        din6 => state_6_i,
        din7 => state_7_i,
        din8 => state_8_i,
        din9 => state_9_i,
        din10 => state_10_i,
        din11 => state_11_i,
        din12 => state_12_i,
        din13 => state_13_i,
        din14 => state_14_i,
        din15 => state_15_i,
        din16 => state_16_i,
        din17 => state_17_i,
        din18 => state_18_i,
        din19 => state_19_i,
        din20 => state_20_i,
        din21 => state_21_i,
        din22 => state_22_i,
        din23 => state_23_i,
        din24 => state_24_i,
        def => tmp_2_fu_588_p51,
        sel => trunc_ln300_reg_815,
        dout => tmp_2_fu_588_p53);

    flow_control_loop_pipe_sequential_init_U : component keccak_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln300_fu_559_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_168 <= add_ln300_fu_565_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_168 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    message_done_1_fu_172_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    message_done_1_fu_172 <= message_done;
                elsif (((tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    message_done_1_fu_172 <= message_done_2_fu_782_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln300_reg_815 <= trunc_ln300_fu_571_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln300_fu_565_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv6_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp1_assign_proc : process(input_stream_TVALID, tmp_1_nbreadreq_fu_188_p6)
    begin
                ap_block_state2_pp0_stage0_iter1_grp1 <= ((tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (input_stream_TVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln300_fu_559_p2)
    begin
        if (((icmp_ln300_fu_559_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_pp0_stage0, i_fu_168, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_168;
        end if; 
    end process;

    icmp_ln300_fu_559_p2 <= "1" when (ap_sig_allocacmp_i_2 = trunc_ln1) else "0";

    input_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, input_stream_TVALID, tmp_1_nbreadreq_fu_188_p6, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_stream_TDATA_blk_n <= input_stream_TVALID;
        else 
            input_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    input_stream_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_stream_TREADY <= ap_const_logic_1;
        else 
            input_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    message_done_1_out <= message_done_1_fu_172;

    message_done_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln300_fu_559_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln300_fu_559_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            message_done_1_out_ap_vld <= ap_const_logic_1;
        else 
            message_done_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    message_done_2_fu_782_p2 <= (message_done_1_fu_172 or input_stream_TLAST);

    state_10_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_10_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_A))) then 
            state_10_o <= state_25_fu_695_p2;
        else 
            state_10_o <= state_10_i;
        end if; 
    end process;


    state_10_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_A))) then 
            state_10_o_ap_vld <= ap_const_logic_1;
        else 
            state_10_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_11_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_11_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_B))) then 
            state_11_o <= state_25_fu_695_p2;
        else 
            state_11_o <= state_11_i;
        end if; 
    end process;


    state_11_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_B))) then 
            state_11_o_ap_vld <= ap_const_logic_1;
        else 
            state_11_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_12_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_12_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_C))) then 
            state_12_o <= state_25_fu_695_p2;
        else 
            state_12_o <= state_12_i;
        end if; 
    end process;


    state_12_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_C))) then 
            state_12_o_ap_vld <= ap_const_logic_1;
        else 
            state_12_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_13_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_13_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_D))) then 
            state_13_o <= state_25_fu_695_p2;
        else 
            state_13_o <= state_13_i;
        end if; 
    end process;


    state_13_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_D))) then 
            state_13_o_ap_vld <= ap_const_logic_1;
        else 
            state_13_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_14_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_14_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_E))) then 
            state_14_o <= state_25_fu_695_p2;
        else 
            state_14_o <= state_14_i;
        end if; 
    end process;


    state_14_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_E))) then 
            state_14_o_ap_vld <= ap_const_logic_1;
        else 
            state_14_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_15_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_15_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_F))) then 
            state_15_o <= state_25_fu_695_p2;
        else 
            state_15_o <= state_15_i;
        end if; 
    end process;


    state_15_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_F))) then 
            state_15_o_ap_vld <= ap_const_logic_1;
        else 
            state_15_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_16_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_16_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_10))) then 
            state_16_o <= state_25_fu_695_p2;
        else 
            state_16_o <= state_16_i;
        end if; 
    end process;


    state_16_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_10))) then 
            state_16_o_ap_vld <= ap_const_logic_1;
        else 
            state_16_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_17_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_17_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_11))) then 
            state_17_o <= state_25_fu_695_p2;
        else 
            state_17_o <= state_17_i;
        end if; 
    end process;


    state_17_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_11))) then 
            state_17_o_ap_vld <= ap_const_logic_1;
        else 
            state_17_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_18_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_18_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_12))) then 
            state_18_o <= state_25_fu_695_p2;
        else 
            state_18_o <= state_18_i;
        end if; 
    end process;


    state_18_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_12))) then 
            state_18_o_ap_vld <= ap_const_logic_1;
        else 
            state_18_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_19_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_19_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_13))) then 
            state_19_o <= state_25_fu_695_p2;
        else 
            state_19_o <= state_19_i;
        end if; 
    end process;


    state_19_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_13))) then 
            state_19_o_ap_vld <= ap_const_logic_1;
        else 
            state_19_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_1_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_1_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_1))) then 
            state_1_o <= state_25_fu_695_p2;
        else 
            state_1_o <= state_1_i;
        end if; 
    end process;


    state_1_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_1))) then 
            state_1_o_ap_vld <= ap_const_logic_1;
        else 
            state_1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_20_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_20_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_14))) then 
            state_20_o <= state_25_fu_695_p2;
        else 
            state_20_o <= state_20_i;
        end if; 
    end process;


    state_20_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_14))) then 
            state_20_o_ap_vld <= ap_const_logic_1;
        else 
            state_20_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_21_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_21_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_15))) then 
            state_21_o <= state_25_fu_695_p2;
        else 
            state_21_o <= state_21_i;
        end if; 
    end process;


    state_21_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_15))) then 
            state_21_o_ap_vld <= ap_const_logic_1;
        else 
            state_21_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_22_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_22_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_16))) then 
            state_22_o <= state_25_fu_695_p2;
        else 
            state_22_o <= state_22_i;
        end if; 
    end process;


    state_22_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_16))) then 
            state_22_o_ap_vld <= ap_const_logic_1;
        else 
            state_22_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_23_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_23_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_17))) then 
            state_23_o <= state_25_fu_695_p2;
        else 
            state_23_o <= state_23_i;
        end if; 
    end process;


    state_23_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_17))) then 
            state_23_o_ap_vld <= ap_const_logic_1;
        else 
            state_23_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_24_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_24_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_18))) then 
            state_24_o <= state_25_fu_695_p2;
        else 
            state_24_o <= state_24_i;
        end if; 
    end process;


    state_24_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_18))) then 
            state_24_o_ap_vld <= ap_const_logic_1;
        else 
            state_24_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    state_25_fu_695_p2 <= (tmp_2_fu_588_p53 xor input_stream_TDATA);

    state_2_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_2_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_2))) then 
            state_2_o <= state_25_fu_695_p2;
        else 
            state_2_o <= state_2_i;
        end if; 
    end process;


    state_2_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_2))) then 
            state_2_o_ap_vld <= ap_const_logic_1;
        else 
            state_2_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_3_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_3_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_3))) then 
            state_3_o <= state_25_fu_695_p2;
        else 
            state_3_o <= state_3_i;
        end if; 
    end process;


    state_3_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_3))) then 
            state_3_o_ap_vld <= ap_const_logic_1;
        else 
            state_3_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_4_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_4_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_4))) then 
            state_4_o <= state_25_fu_695_p2;
        else 
            state_4_o <= state_4_i;
        end if; 
    end process;


    state_4_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_4))) then 
            state_4_o_ap_vld <= ap_const_logic_1;
        else 
            state_4_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_5_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_5_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_5))) then 
            state_5_o <= state_25_fu_695_p2;
        else 
            state_5_o <= state_5_i;
        end if; 
    end process;


    state_5_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_5))) then 
            state_5_o_ap_vld <= ap_const_logic_1;
        else 
            state_5_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_6_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_6_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_6))) then 
            state_6_o <= state_25_fu_695_p2;
        else 
            state_6_o <= state_6_i;
        end if; 
    end process;


    state_6_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_6))) then 
            state_6_o_ap_vld <= ap_const_logic_1;
        else 
            state_6_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_7_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_7_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_7))) then 
            state_7_o <= state_25_fu_695_p2;
        else 
            state_7_o <= state_7_i;
        end if; 
    end process;


    state_7_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_7))) then 
            state_7_o_ap_vld <= ap_const_logic_1;
        else 
            state_7_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_8_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_8_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_8))) then 
            state_8_o <= state_25_fu_695_p2;
        else 
            state_8_o <= state_8_i;
        end if; 
    end process;


    state_8_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_8))) then 
            state_8_o_ap_vld <= ap_const_logic_1;
        else 
            state_8_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_9_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_9_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_9))) then 
            state_9_o <= state_25_fu_695_p2;
        else 
            state_9_o <= state_9_i;
        end if; 
    end process;


    state_9_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_9))) then 
            state_9_o_ap_vld <= ap_const_logic_1;
        else 
            state_9_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    state_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, state_i, trunc_ln300_reg_815, state_25_fu_695_p2, ap_block_pp0_stage0_01001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_0))) then 
            state_o <= state_25_fu_695_p2;
        else 
            state_o <= state_i;
        end if; 
    end process;


    state_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_1_nbreadreq_fu_188_p6, trunc_ln300_reg_815, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (tmp_1_nbreadreq_fu_188_p6 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln300_reg_815 = ap_const_lv5_0))) then 
            state_o_ap_vld <= ap_const_logic_1;
        else 
            state_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_nbreadreq_fu_188_p6 <= (0=>(input_stream_TVALID), others=>'-');
    tmp_2_fu_588_p51 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    trunc_ln300_fu_571_p1 <= ap_sig_allocacmp_i_2(5 - 1 downto 0);
end behav;
