// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module keccak_top_keccak_f1600 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        state_0_read,
        state_1_read,
        state_2_read,
        state_3_read,
        state_4_read,
        state_5_read,
        state_6_read,
        state_7_read,
        state_8_read,
        state_9_read,
        state_10_read,
        state_11_read,
        state_1213_read,
        state_13_read,
        state_14_read,
        state_15_read,
        state_16_read,
        state_17_read,
        state_18_read,
        state_19_read,
        state_20_read,
        state_21_read,
        state_22_read,
        state_2325_read,
        state_24_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] state_0_read;
input  [63:0] state_1_read;
input  [63:0] state_2_read;
input  [63:0] state_3_read;
input  [63:0] state_4_read;
input  [63:0] state_5_read;
input  [63:0] state_6_read;
input  [63:0] state_7_read;
input  [63:0] state_8_read;
input  [63:0] state_9_read;
input  [63:0] state_10_read;
input  [63:0] state_11_read;
input  [63:0] state_1213_read;
input  [63:0] state_13_read;
input  [63:0] state_14_read;
input  [63:0] state_15_read;
input  [63:0] state_16_read;
input  [63:0] state_17_read;
input  [63:0] state_18_read;
input  [63:0] state_19_read;
input  [63:0] state_20_read;
input  [63:0] state_21_read;
input  [63:0] state_22_read;
input  [63:0] state_2325_read;
input  [63:0] state_24_read;
output  [63:0] ap_return_0;
output  [63:0] ap_return_1;
output  [63:0] ap_return_2;
output  [63:0] ap_return_3;
output  [63:0] ap_return_4;
output  [63:0] ap_return_5;
output  [63:0] ap_return_6;
output  [63:0] ap_return_7;
output  [63:0] ap_return_8;
output  [63:0] ap_return_9;
output  [63:0] ap_return_10;
output  [63:0] ap_return_11;
output  [63:0] ap_return_12;
output  [63:0] ap_return_13;
output  [63:0] ap_return_14;
output  [63:0] ap_return_15;
output  [63:0] ap_return_16;
output  [63:0] ap_return_17;
output  [63:0] ap_return_18;
output  [63:0] ap_return_19;
output  [63:0] ap_return_20;
output  [63:0] ap_return_21;
output  [63:0] ap_return_22;
output  [63:0] ap_return_23;
output  [63:0] ap_return_24;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln157_fu_628_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [4:0] RC_TABLE_address0;
wire   [63:0] RC_TABLE_q0;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln157_fu_640_p1;
wire    ap_block_pp0_stage0;
reg   [63:0] state_3_0_fu_228;
wire   [63:0] xor_ln135_5_fu_1699_p2;
reg   [63:0] ap_sig_allocacmp_state_3_0_load_1;
wire    ap_loop_init;
reg   [63:0] state_0_0_fu_232;
wire   [63:0] xor_ln145_2_fu_2101_p2;
reg   [63:0] ap_sig_allocacmp_state_0_0_load_1;
reg   [63:0] state_5_0_fu_236;
wire   [63:0] xor_ln135_9_fu_1735_p2;
reg   [63:0] ap_sig_allocacmp_state_5_0_load_1;
reg   [63:0] state_10_0_fu_240;
wire   [63:0] xor_ln135_19_fu_1825_p2;
reg   [63:0] ap_sig_allocacmp_state_10_0_load_1;
reg   [63:0] state_1549_0_fu_244;
wire   [63:0] xor_ln135_29_fu_1915_p2;
reg   [63:0] ap_sig_allocacmp_state_1549_0_load_1;
reg   [63:0] state_20_0_fu_248;
wire   [63:0] xor_ln135_39_fu_2005_p2;
reg   [63:0] ap_sig_allocacmp_state_20_0_load_1;
reg   [63:0] state_1_0_fu_252;
wire   [63:0] xor_ln135_1_fu_1663_p2;
reg   [63:0] ap_sig_allocacmp_state_1_0_load_1;
reg   [63:0] state_6_0_fu_256;
wire   [63:0] xor_ln135_11_fu_1753_p2;
reg   [63:0] ap_sig_allocacmp_state_6_0_load_1;
reg   [63:0] state_11_0_fu_260;
wire   [63:0] xor_ln135_21_fu_1843_p2;
reg   [63:0] ap_sig_allocacmp_state_11_0_load_1;
reg   [63:0] state_16_0_fu_264;
wire   [63:0] xor_ln135_31_fu_1933_p2;
reg   [63:0] ap_sig_allocacmp_state_16_0_load_1;
reg   [63:0] state_21_0_fu_268;
wire   [63:0] xor_ln135_41_fu_2023_p2;
reg   [63:0] ap_sig_allocacmp_state_21_0_load_1;
reg   [63:0] state_2_0_fu_272;
wire   [63:0] xor_ln135_3_fu_1681_p2;
reg   [63:0] ap_sig_allocacmp_state_2_0_load_1;
reg   [63:0] state_7_0_fu_276;
wire   [63:0] xor_ln135_13_fu_1771_p2;
reg   [63:0] ap_sig_allocacmp_state_7_0_load_1;
reg   [63:0] state_1213_0_fu_280;
wire   [63:0] xor_ln135_23_fu_1861_p2;
reg   [63:0] ap_sig_allocacmp_state_1213_0_load_1;
reg   [63:0] state_17_0_fu_284;
wire   [63:0] xor_ln135_33_fu_1951_p2;
reg   [63:0] ap_sig_allocacmp_state_17_0_load_1;
reg   [63:0] state_22_0_fu_288;
wire   [63:0] xor_ln135_43_fu_2041_p2;
reg   [63:0] ap_sig_allocacmp_state_22_0_load_1;
reg   [63:0] state_8_0_fu_292;
wire   [63:0] xor_ln135_15_fu_1789_p2;
reg   [63:0] ap_sig_allocacmp_state_8_0_load_1;
reg   [63:0] state_13_0_fu_296;
wire   [63:0] xor_ln135_25_fu_1879_p2;
reg   [63:0] ap_sig_allocacmp_state_13_0_load_1;
reg   [63:0] state_18_0_fu_300;
wire   [63:0] xor_ln135_35_fu_1969_p2;
reg   [63:0] ap_sig_allocacmp_state_18_0_load_1;
reg   [63:0] state_2325_0_fu_304;
wire   [63:0] xor_ln135_45_fu_2059_p2;
reg   [63:0] ap_sig_allocacmp_state_2325_0_load_1;
reg   [63:0] state_4_0_fu_308;
wire   [63:0] xor_ln135_7_fu_1717_p2;
reg   [63:0] ap_sig_allocacmp_state_4_0_load_1;
reg   [63:0] state_9_0_fu_312;
wire   [63:0] xor_ln135_17_fu_1807_p2;
reg   [63:0] ap_sig_allocacmp_state_9_0_load_1;
reg   [63:0] state_14_0_fu_316;
wire   [63:0] xor_ln135_27_fu_1897_p2;
reg   [63:0] ap_sig_allocacmp_state_14_0_load_1;
reg   [63:0] state_19_0_fu_320;
wire   [63:0] xor_ln135_37_fu_1987_p2;
reg   [63:0] ap_sig_allocacmp_state_19_0_load_1;
reg   [63:0] state_24_0_fu_324;
wire   [63:0] xor_ln135_47_fu_2077_p2;
reg   [63:0] ap_sig_allocacmp_state_24_0_load_1;
reg   [4:0] round_fu_328;
wire   [4:0] add_ln157_fu_634_p2;
reg   [4:0] ap_sig_allocacmp_round_1;
reg    RC_TABLE_ce0_local;
wire   [63:0] xor_ln50_1_fu_731_p2;
wire   [63:0] xor_ln50_2_fu_737_p2;
wire   [63:0] xor_ln50_fu_725_p2;
wire   [63:0] xor_ln50_5_fu_755_p2;
wire   [63:0] xor_ln50_6_fu_761_p2;
wire   [63:0] xor_ln50_4_fu_749_p2;
wire   [63:0] xor_ln50_9_fu_779_p2;
wire   [63:0] xor_ln50_10_fu_785_p2;
wire   [63:0] xor_ln50_8_fu_773_p2;
wire   [63:0] xor_ln50_13_fu_803_p2;
wire   [63:0] xor_ln50_14_fu_809_p2;
wire   [63:0] xor_ln50_12_fu_797_p2;
wire   [63:0] xor_ln50_17_fu_827_p2;
wire   [63:0] xor_ln50_18_fu_833_p2;
wire   [63:0] xor_ln50_16_fu_821_p2;
wire   [63:0] x_fu_767_p2;
wire   [62:0] trunc_ln22_fu_845_p1;
wire   [0:0] tmp_fu_849_p3;
wire   [63:0] or_ln_fu_857_p3;
wire   [63:0] x_3_fu_839_p2;
wire   [63:0] x_1_fu_791_p2;
wire   [62:0] trunc_ln22_1_fu_871_p1;
wire   [0:0] tmp_16_fu_875_p3;
wire   [63:0] x_4_fu_743_p2;
wire   [63:0] or_ln22_1_fu_883_p3;
wire   [63:0] x_2_fu_815_p2;
wire   [62:0] trunc_ln22_2_fu_897_p1;
wire   [0:0] tmp_17_fu_901_p3;
wire   [63:0] or_ln22_2_fu_909_p3;
wire   [62:0] trunc_ln22_3_fu_923_p1;
wire   [0:0] tmp_18_fu_927_p3;
wire   [63:0] or_ln22_3_fu_935_p3;
wire   [62:0] trunc_ln22_4_fu_949_p1;
wire   [0:0] tmp_19_fu_953_p3;
wire   [63:0] or_ln22_4_fu_961_p3;
wire   [63:0] xor_ln57_fu_865_p2;
wire   [63:0] xor_ln57_1_fu_891_p2;
wire   [63:0] xor_ln57_2_fu_917_p2;
wire   [63:0] xor_ln57_3_fu_943_p2;
wire   [63:0] xor_ln57_4_fu_969_p2;
wire   [63:0] x_5_fu_981_p2;
wire   [62:0] trunc_ln22_5_fu_1125_p1;
wire   [0:0] tmp_20_fu_1129_p3;
wire   [63:0] x_6_fu_1035_p2;
wire   [60:0] trunc_ln22_6_fu_1145_p1;
wire   [2:0] lshr_ln22_6_fu_1149_p4;
wire   [63:0] x_7_fu_1017_p2;
wire   [57:0] trunc_ln22_7_fu_1167_p1;
wire   [5:0] lshr_ln22_7_fu_1171_p4;
wire   [63:0] x_8_fu_1041_p2;
wire   [53:0] trunc_ln22_8_fu_1189_p1;
wire   [9:0] lshr_ln22_8_fu_1193_p4;
wire   [63:0] x_9_fu_1077_p2;
wire   [48:0] trunc_ln22_9_fu_1211_p1;
wire   [14:0] lshr_ln22_9_fu_1215_p4;
wire   [63:0] x_10_fu_1083_p2;
wire   [42:0] trunc_ln22_10_fu_1233_p1;
wire   [20:0] lshr_ln22_s_fu_1237_p4;
wire   [63:0] x_11_fu_993_p2;
wire   [35:0] trunc_ln22_11_fu_1255_p1;
wire   [27:0] lshr_ln22_1_fu_1259_p4;
wire   [63:0] x_12_fu_1005_p2;
wire   [27:0] trunc_ln22_12_fu_1277_p1;
wire   [35:0] lshr_ln22_2_fu_1281_p4;
wire   [63:0] x_13_fu_1071_p2;
wire   [18:0] trunc_ln22_13_fu_1299_p1;
wire   [44:0] lshr_ln22_3_fu_1303_p4;
wire   [63:0] x_14_fu_1023_p2;
wire   [8:0] trunc_ln22_14_fu_1321_p1;
wire   [54:0] lshr_ln22_4_fu_1325_p4;
wire   [63:0] x_15_fu_1101_p2;
wire   [61:0] trunc_ln22_15_fu_1343_p1;
wire   [1:0] lshr_ln22_5_fu_1347_p4;
wire   [63:0] x_16_fu_1119_p2;
wire   [49:0] trunc_ln22_16_fu_1365_p1;
wire   [13:0] lshr_ln22_10_fu_1369_p4;
wire   [63:0] x_17_fu_999_p2;
wire   [36:0] trunc_ln22_17_fu_1387_p1;
wire   [26:0] lshr_ln22_11_fu_1391_p4;
wire   [63:0] x_18_fu_1065_p2;
wire   [22:0] trunc_ln22_18_fu_1409_p1;
wire   [40:0] lshr_ln22_12_fu_1413_p4;
wire   [63:0] x_19_fu_1113_p2;
wire   [7:0] trunc_ln22_19_fu_1431_p1;
wire   [55:0] lshr_ln22_13_fu_1435_p4;
wire   [63:0] x_20_fu_1089_p2;
wire   [55:0] trunc_ln22_20_fu_1453_p1;
wire   [7:0] lshr_ln22_14_fu_1457_p4;
wire   [63:0] x_21_fu_1053_p2;
wire   [38:0] trunc_ln22_21_fu_1475_p1;
wire   [24:0] lshr_ln22_15_fu_1479_p4;
wire   [63:0] x_22_fu_1047_p2;
wire   [20:0] trunc_ln22_22_fu_1497_p1;
wire   [42:0] lshr_ln22_16_fu_1501_p4;
wire   [63:0] x_23_fu_987_p2;
wire   [1:0] trunc_ln22_23_fu_1519_p1;
wire   [61:0] lshr_ln22_17_fu_1523_p4;
wire   [63:0] x_24_fu_1095_p2;
wire   [45:0] trunc_ln22_24_fu_1541_p1;
wire   [17:0] lshr_ln22_18_fu_1545_p4;
wire   [63:0] x_25_fu_1059_p2;
wire   [24:0] trunc_ln22_25_fu_1563_p1;
wire   [38:0] lshr_ln22_19_fu_1567_p4;
wire   [63:0] x_26_fu_1107_p2;
wire   [2:0] trunc_ln22_26_fu_1585_p1;
wire   [60:0] lshr_ln22_20_fu_1589_p4;
wire   [63:0] x_27_fu_1029_p2;
wire   [43:0] trunc_ln22_27_fu_1607_p1;
wire   [19:0] lshr_ln22_21_fu_1611_p4;
wire   [63:0] x_28_fu_1011_p2;
wire   [19:0] trunc_ln22_28_fu_1629_p1;
wire   [43:0] lshr_ln22_22_fu_1633_p4;
wire   [63:0] or_ln22_21_fu_1511_p3;
wire   [63:0] or_ln22_s_fu_1247_p3;
wire   [63:0] xor_ln135_fu_1651_p2;
wire   [63:0] or_ln22_27_fu_1643_p3;
wire   [63:0] and_ln135_fu_1657_p2;
wire   [63:0] or_ln22_15_fu_1379_p3;
wire   [63:0] xor_ln135_2_fu_1669_p2;
wire   [63:0] and_ln135_1_fu_1675_p2;
wire   [63:0] xor_ln67_fu_975_p2;
wire   [63:0] xor_ln135_4_fu_1687_p2;
wire   [63:0] and_ln135_2_fu_1693_p2;
wire   [63:0] xor_ln135_6_fu_1705_p2;
wire   [63:0] and_ln135_3_fu_1711_p2;
wire   [63:0] or_ln22_26_fu_1621_p3;
wire   [63:0] or_ln22_6_fu_1159_p3;
wire   [63:0] xor_ln135_8_fu_1723_p2;
wire   [63:0] and_ln135_4_fu_1729_p2;
wire   [63:0] or_ln22_10_fu_1269_p3;
wire   [63:0] or_ln22_12_fu_1313_p3;
wire   [63:0] xor_ln135_10_fu_1741_p2;
wire   [63:0] and_ln135_5_fu_1747_p2;
wire   [63:0] or_ln22_25_fu_1599_p3;
wire   [63:0] xor_ln135_12_fu_1759_p2;
wire   [63:0] and_ln135_6_fu_1765_p2;
wire   [63:0] xor_ln135_14_fu_1777_p2;
wire   [63:0] and_ln135_7_fu_1783_p2;
wire   [63:0] xor_ln135_16_fu_1795_p2;
wire   [63:0] and_ln135_8_fu_1801_p2;
wire   [63:0] or_ln22_7_fu_1181_p3;
wire   [63:0] or_ln22_20_fu_1489_p3;
wire   [63:0] xor_ln135_18_fu_1813_p2;
wire   [63:0] or_ln22_5_fu_1137_p3;
wire   [63:0] and_ln135_9_fu_1819_p2;
wire   [63:0] or_ln22_19_fu_1467_p3;
wire   [63:0] xor_ln135_20_fu_1831_p2;
wire   [63:0] and_ln135_10_fu_1837_p2;
wire   [63:0] or_ln22_23_fu_1555_p3;
wire   [63:0] xor_ln135_22_fu_1849_p2;
wire   [63:0] and_ln135_11_fu_1855_p2;
wire   [63:0] xor_ln135_24_fu_1867_p2;
wire   [63:0] and_ln135_12_fu_1873_p2;
wire   [63:0] xor_ln135_26_fu_1885_p2;
wire   [63:0] and_ln135_13_fu_1891_p2;
wire   [63:0] or_ln22_11_fu_1291_p3;
wire   [63:0] or_ln22_8_fu_1203_p3;
wire   [63:0] xor_ln135_28_fu_1903_p2;
wire   [63:0] or_ln22_16_fu_1401_p3;
wire   [63:0] and_ln135_14_fu_1909_p2;
wire   [63:0] or_ln22_9_fu_1225_p3;
wire   [63:0] xor_ln135_30_fu_1921_p2;
wire   [63:0] and_ln135_15_fu_1927_p2;
wire   [63:0] or_ln22_18_fu_1445_p3;
wire   [63:0] xor_ln135_32_fu_1939_p2;
wire   [63:0] and_ln135_16_fu_1945_p2;
wire   [63:0] xor_ln135_34_fu_1957_p2;
wire   [63:0] and_ln135_17_fu_1963_p2;
wire   [63:0] xor_ln135_36_fu_1975_p2;
wire   [63:0] and_ln135_18_fu_1981_p2;
wire   [63:0] or_ln22_13_fu_1335_p3;
wire   [63:0] or_ln22_24_fu_1577_p3;
wire   [63:0] xor_ln135_38_fu_1993_p2;
wire   [63:0] and_ln135_19_fu_1999_p2;
wire   [63:0] or_ln22_22_fu_1533_p3;
wire   [63:0] or_ln22_17_fu_1423_p3;
wire   [63:0] xor_ln135_40_fu_2011_p2;
wire   [63:0] and_ln135_20_fu_2017_p2;
wire   [63:0] or_ln22_14_fu_1357_p3;
wire   [63:0] xor_ln135_42_fu_2029_p2;
wire   [63:0] and_ln135_21_fu_2035_p2;
wire   [63:0] xor_ln135_44_fu_2047_p2;
wire   [63:0] and_ln135_22_fu_2053_p2;
wire   [63:0] xor_ln135_46_fu_2065_p2;
wire   [63:0] and_ln135_23_fu_2071_p2;
wire   [63:0] xor_ln145_fu_2083_p2;
wire   [63:0] and_ln145_fu_2089_p2;
wire   [63:0] xor_ln145_1_fu_2095_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 state_3_0_fu_228 = 64'd0;
#0 state_0_0_fu_232 = 64'd0;
#0 state_5_0_fu_236 = 64'd0;
#0 state_10_0_fu_240 = 64'd0;
#0 state_1549_0_fu_244 = 64'd0;
#0 state_20_0_fu_248 = 64'd0;
#0 state_1_0_fu_252 = 64'd0;
#0 state_6_0_fu_256 = 64'd0;
#0 state_11_0_fu_260 = 64'd0;
#0 state_16_0_fu_264 = 64'd0;
#0 state_21_0_fu_268 = 64'd0;
#0 state_2_0_fu_272 = 64'd0;
#0 state_7_0_fu_276 = 64'd0;
#0 state_1213_0_fu_280 = 64'd0;
#0 state_17_0_fu_284 = 64'd0;
#0 state_22_0_fu_288 = 64'd0;
#0 state_8_0_fu_292 = 64'd0;
#0 state_13_0_fu_296 = 64'd0;
#0 state_18_0_fu_300 = 64'd0;
#0 state_2325_0_fu_304 = 64'd0;
#0 state_4_0_fu_308 = 64'd0;
#0 state_9_0_fu_312 = 64'd0;
#0 state_14_0_fu_316 = 64'd0;
#0 state_19_0_fu_320 = 64'd0;
#0 state_24_0_fu_324 = 64'd0;
#0 round_fu_328 = 5'd0;
#0 ap_done_reg = 1'b0;
end

keccak_top_keccak_f1600_RC_TABLE_ROM_AUTO_1R #(
    .DataWidth( 64 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
RC_TABLE_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RC_TABLE_address0),
    .ce0(RC_TABLE_ce0_local),
    .q0(RC_TABLE_q0)
);

keccak_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln157_fu_628_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            round_fu_328 <= add_ln157_fu_634_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            round_fu_328 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_0_0_fu_232 <= state_0_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_0_0_fu_232 <= xor_ln145_2_fu_2101_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_10_0_fu_240 <= state_10_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_10_0_fu_240 <= xor_ln135_19_fu_1825_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_11_0_fu_260 <= state_11_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_11_0_fu_260 <= xor_ln135_21_fu_1843_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_1213_0_fu_280 <= state_1213_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_1213_0_fu_280 <= xor_ln135_23_fu_1861_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_13_0_fu_296 <= state_13_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_13_0_fu_296 <= xor_ln135_25_fu_1879_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_14_0_fu_316 <= state_14_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_14_0_fu_316 <= xor_ln135_27_fu_1897_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_1549_0_fu_244 <= state_15_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_1549_0_fu_244 <= xor_ln135_29_fu_1915_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_16_0_fu_264 <= state_16_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_16_0_fu_264 <= xor_ln135_31_fu_1933_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_17_0_fu_284 <= state_17_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_17_0_fu_284 <= xor_ln135_33_fu_1951_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_18_0_fu_300 <= state_18_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_18_0_fu_300 <= xor_ln135_35_fu_1969_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_19_0_fu_320 <= state_19_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_19_0_fu_320 <= xor_ln135_37_fu_1987_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_1_0_fu_252 <= state_1_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_1_0_fu_252 <= xor_ln135_1_fu_1663_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_20_0_fu_248 <= state_20_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_20_0_fu_248 <= xor_ln135_39_fu_2005_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_21_0_fu_268 <= state_21_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_21_0_fu_268 <= xor_ln135_41_fu_2023_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_22_0_fu_288 <= state_22_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_22_0_fu_288 <= xor_ln135_43_fu_2041_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_2325_0_fu_304 <= state_2325_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_2325_0_fu_304 <= xor_ln135_45_fu_2059_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_24_0_fu_324 <= state_24_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_24_0_fu_324 <= xor_ln135_47_fu_2077_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_2_0_fu_272 <= state_2_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_2_0_fu_272 <= xor_ln135_3_fu_1681_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_3_0_fu_228 <= state_3_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_3_0_fu_228 <= xor_ln135_5_fu_1699_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_4_0_fu_308 <= state_4_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_4_0_fu_308 <= xor_ln135_7_fu_1717_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_5_0_fu_236 <= state_5_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_5_0_fu_236 <= xor_ln135_9_fu_1735_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_6_0_fu_256 <= state_6_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_6_0_fu_256 <= xor_ln135_11_fu_1753_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_7_0_fu_276 <= state_7_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_7_0_fu_276 <= xor_ln135_13_fu_1771_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_8_0_fu_292 <= state_8_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_8_0_fu_292 <= xor_ln135_15_fu_1789_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            state_9_0_fu_312 <= state_9_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            state_9_0_fu_312 <= xor_ln135_17_fu_1807_p2;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        RC_TABLE_ce0_local = 1'b1;
    end else begin
        RC_TABLE_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln157_fu_628_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_round_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_round_1 = round_fu_328;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_0_0_load_1 = state_0_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_0_0_load_1 = xor_ln145_2_fu_2101_p2;
        end else begin
            ap_sig_allocacmp_state_0_0_load_1 = state_0_0_fu_232;
        end
    end else begin
        ap_sig_allocacmp_state_0_0_load_1 = state_0_0_fu_232;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_10_0_load_1 = state_10_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_10_0_load_1 = xor_ln135_19_fu_1825_p2;
        end else begin
            ap_sig_allocacmp_state_10_0_load_1 = state_10_0_fu_240;
        end
    end else begin
        ap_sig_allocacmp_state_10_0_load_1 = state_10_0_fu_240;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_11_0_load_1 = state_11_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_11_0_load_1 = xor_ln135_21_fu_1843_p2;
        end else begin
            ap_sig_allocacmp_state_11_0_load_1 = state_11_0_fu_260;
        end
    end else begin
        ap_sig_allocacmp_state_11_0_load_1 = state_11_0_fu_260;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_1213_0_load_1 = state_1213_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_1213_0_load_1 = xor_ln135_23_fu_1861_p2;
        end else begin
            ap_sig_allocacmp_state_1213_0_load_1 = state_1213_0_fu_280;
        end
    end else begin
        ap_sig_allocacmp_state_1213_0_load_1 = state_1213_0_fu_280;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_13_0_load_1 = state_13_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_13_0_load_1 = xor_ln135_25_fu_1879_p2;
        end else begin
            ap_sig_allocacmp_state_13_0_load_1 = state_13_0_fu_296;
        end
    end else begin
        ap_sig_allocacmp_state_13_0_load_1 = state_13_0_fu_296;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_14_0_load_1 = state_14_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_14_0_load_1 = xor_ln135_27_fu_1897_p2;
        end else begin
            ap_sig_allocacmp_state_14_0_load_1 = state_14_0_fu_316;
        end
    end else begin
        ap_sig_allocacmp_state_14_0_load_1 = state_14_0_fu_316;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_1549_0_load_1 = state_15_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_1549_0_load_1 = xor_ln135_29_fu_1915_p2;
        end else begin
            ap_sig_allocacmp_state_1549_0_load_1 = state_1549_0_fu_244;
        end
    end else begin
        ap_sig_allocacmp_state_1549_0_load_1 = state_1549_0_fu_244;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_16_0_load_1 = state_16_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_16_0_load_1 = xor_ln135_31_fu_1933_p2;
        end else begin
            ap_sig_allocacmp_state_16_0_load_1 = state_16_0_fu_264;
        end
    end else begin
        ap_sig_allocacmp_state_16_0_load_1 = state_16_0_fu_264;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_17_0_load_1 = state_17_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_17_0_load_1 = xor_ln135_33_fu_1951_p2;
        end else begin
            ap_sig_allocacmp_state_17_0_load_1 = state_17_0_fu_284;
        end
    end else begin
        ap_sig_allocacmp_state_17_0_load_1 = state_17_0_fu_284;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_18_0_load_1 = state_18_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_18_0_load_1 = xor_ln135_35_fu_1969_p2;
        end else begin
            ap_sig_allocacmp_state_18_0_load_1 = state_18_0_fu_300;
        end
    end else begin
        ap_sig_allocacmp_state_18_0_load_1 = state_18_0_fu_300;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_19_0_load_1 = state_19_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_19_0_load_1 = xor_ln135_37_fu_1987_p2;
        end else begin
            ap_sig_allocacmp_state_19_0_load_1 = state_19_0_fu_320;
        end
    end else begin
        ap_sig_allocacmp_state_19_0_load_1 = state_19_0_fu_320;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_1_0_load_1 = state_1_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_1_0_load_1 = xor_ln135_1_fu_1663_p2;
        end else begin
            ap_sig_allocacmp_state_1_0_load_1 = state_1_0_fu_252;
        end
    end else begin
        ap_sig_allocacmp_state_1_0_load_1 = state_1_0_fu_252;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_20_0_load_1 = state_20_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_20_0_load_1 = xor_ln135_39_fu_2005_p2;
        end else begin
            ap_sig_allocacmp_state_20_0_load_1 = state_20_0_fu_248;
        end
    end else begin
        ap_sig_allocacmp_state_20_0_load_1 = state_20_0_fu_248;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_21_0_load_1 = state_21_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_21_0_load_1 = xor_ln135_41_fu_2023_p2;
        end else begin
            ap_sig_allocacmp_state_21_0_load_1 = state_21_0_fu_268;
        end
    end else begin
        ap_sig_allocacmp_state_21_0_load_1 = state_21_0_fu_268;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_22_0_load_1 = state_22_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_22_0_load_1 = xor_ln135_43_fu_2041_p2;
        end else begin
            ap_sig_allocacmp_state_22_0_load_1 = state_22_0_fu_288;
        end
    end else begin
        ap_sig_allocacmp_state_22_0_load_1 = state_22_0_fu_288;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_2325_0_load_1 = state_2325_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_2325_0_load_1 = xor_ln135_45_fu_2059_p2;
        end else begin
            ap_sig_allocacmp_state_2325_0_load_1 = state_2325_0_fu_304;
        end
    end else begin
        ap_sig_allocacmp_state_2325_0_load_1 = state_2325_0_fu_304;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_24_0_load_1 = state_24_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_24_0_load_1 = xor_ln135_47_fu_2077_p2;
        end else begin
            ap_sig_allocacmp_state_24_0_load_1 = state_24_0_fu_324;
        end
    end else begin
        ap_sig_allocacmp_state_24_0_load_1 = state_24_0_fu_324;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_2_0_load_1 = state_2_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_2_0_load_1 = xor_ln135_3_fu_1681_p2;
        end else begin
            ap_sig_allocacmp_state_2_0_load_1 = state_2_0_fu_272;
        end
    end else begin
        ap_sig_allocacmp_state_2_0_load_1 = state_2_0_fu_272;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_3_0_load_1 = state_3_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_3_0_load_1 = xor_ln135_5_fu_1699_p2;
        end else begin
            ap_sig_allocacmp_state_3_0_load_1 = state_3_0_fu_228;
        end
    end else begin
        ap_sig_allocacmp_state_3_0_load_1 = state_3_0_fu_228;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_4_0_load_1 = state_4_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_4_0_load_1 = xor_ln135_7_fu_1717_p2;
        end else begin
            ap_sig_allocacmp_state_4_0_load_1 = state_4_0_fu_308;
        end
    end else begin
        ap_sig_allocacmp_state_4_0_load_1 = state_4_0_fu_308;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_5_0_load_1 = state_5_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_5_0_load_1 = xor_ln135_9_fu_1735_p2;
        end else begin
            ap_sig_allocacmp_state_5_0_load_1 = state_5_0_fu_236;
        end
    end else begin
        ap_sig_allocacmp_state_5_0_load_1 = state_5_0_fu_236;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_6_0_load_1 = state_6_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_6_0_load_1 = xor_ln135_11_fu_1753_p2;
        end else begin
            ap_sig_allocacmp_state_6_0_load_1 = state_6_0_fu_256;
        end
    end else begin
        ap_sig_allocacmp_state_6_0_load_1 = state_6_0_fu_256;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_7_0_load_1 = state_7_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_7_0_load_1 = xor_ln135_13_fu_1771_p2;
        end else begin
            ap_sig_allocacmp_state_7_0_load_1 = state_7_0_fu_276;
        end
    end else begin
        ap_sig_allocacmp_state_7_0_load_1 = state_7_0_fu_276;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_8_0_load_1 = state_8_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_8_0_load_1 = xor_ln135_15_fu_1789_p2;
        end else begin
            ap_sig_allocacmp_state_8_0_load_1 = state_8_0_fu_292;
        end
    end else begin
        ap_sig_allocacmp_state_8_0_load_1 = state_8_0_fu_292;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_state_9_0_load_1 = state_9_read;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_state_9_0_load_1 = xor_ln135_17_fu_1807_p2;
        end else begin
            ap_sig_allocacmp_state_9_0_load_1 = state_9_0_fu_312;
        end
    end else begin
        ap_sig_allocacmp_state_9_0_load_1 = state_9_0_fu_312;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign RC_TABLE_address0 = zext_ln157_fu_640_p1;

assign add_ln157_fu_634_p2 = (ap_sig_allocacmp_round_1 + 5'd1);

assign and_ln135_10_fu_1837_p2 = (xor_ln135_20_fu_1831_p2 & or_ln22_19_fu_1467_p3);

assign and_ln135_11_fu_1855_p2 = (xor_ln135_22_fu_1849_p2 & or_ln22_23_fu_1555_p3);

assign and_ln135_12_fu_1873_p2 = (xor_ln135_24_fu_1867_p2 & or_ln22_5_fu_1137_p3);

assign and_ln135_13_fu_1891_p2 = (xor_ln135_26_fu_1885_p2 & or_ln22_7_fu_1181_p3);

assign and_ln135_14_fu_1909_p2 = (xor_ln135_28_fu_1903_p2 & or_ln22_8_fu_1203_p3);

assign and_ln135_15_fu_1927_p2 = (xor_ln135_30_fu_1921_p2 & or_ln22_9_fu_1225_p3);

assign and_ln135_16_fu_1945_p2 = (xor_ln135_32_fu_1939_p2 & or_ln22_18_fu_1445_p3);

assign and_ln135_17_fu_1963_p2 = (xor_ln135_34_fu_1957_p2 & or_ln22_16_fu_1401_p3);

assign and_ln135_18_fu_1981_p2 = (xor_ln135_36_fu_1975_p2 & or_ln22_11_fu_1291_p3);

assign and_ln135_19_fu_1999_p2 = (xor_ln135_38_fu_1993_p2 & or_ln22_24_fu_1577_p3);

assign and_ln135_1_fu_1675_p2 = (xor_ln135_2_fu_1669_p2 & or_ln22_15_fu_1379_p3);

assign and_ln135_20_fu_2017_p2 = (xor_ln135_40_fu_2011_p2 & or_ln22_17_fu_1423_p3);

assign and_ln135_21_fu_2035_p2 = (xor_ln135_42_fu_2029_p2 & or_ln22_14_fu_1357_p3);

assign and_ln135_22_fu_2053_p2 = (xor_ln135_44_fu_2047_p2 & or_ln22_22_fu_1533_p3);

assign and_ln135_23_fu_2071_p2 = (xor_ln135_46_fu_2065_p2 & or_ln22_13_fu_1335_p3);

assign and_ln135_2_fu_1693_p2 = (xor_ln67_fu_975_p2 & xor_ln135_4_fu_1687_p2);

assign and_ln135_3_fu_1711_p2 = (xor_ln135_6_fu_1705_p2 & or_ln22_27_fu_1643_p3);

assign and_ln135_4_fu_1729_p2 = (xor_ln135_8_fu_1723_p2 & or_ln22_6_fu_1159_p3);

assign and_ln135_5_fu_1747_p2 = (xor_ln135_10_fu_1741_p2 & or_ln22_12_fu_1313_p3);

assign and_ln135_6_fu_1765_p2 = (xor_ln135_12_fu_1759_p2 & or_ln22_25_fu_1599_p3);

assign and_ln135_7_fu_1783_p2 = (xor_ln135_14_fu_1777_p2 & or_ln22_10_fu_1269_p3);

assign and_ln135_8_fu_1801_p2 = (xor_ln135_16_fu_1795_p2 & or_ln22_26_fu_1621_p3);

assign and_ln135_9_fu_1819_p2 = (xor_ln135_18_fu_1813_p2 & or_ln22_20_fu_1489_p3);

assign and_ln135_fu_1657_p2 = (xor_ln135_fu_1651_p2 & or_ln22_s_fu_1247_p3);

assign and_ln145_fu_2089_p2 = (xor_ln145_fu_2083_p2 & or_ln22_21_fu_1511_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign ap_return_0 = ap_sig_allocacmp_state_0_0_load_1;

assign ap_return_1 = ap_sig_allocacmp_state_1_0_load_1;

assign ap_return_10 = ap_sig_allocacmp_state_10_0_load_1;

assign ap_return_11 = ap_sig_allocacmp_state_11_0_load_1;

assign ap_return_12 = ap_sig_allocacmp_state_1213_0_load_1;

assign ap_return_13 = ap_sig_allocacmp_state_13_0_load_1;

assign ap_return_14 = ap_sig_allocacmp_state_14_0_load_1;

assign ap_return_15 = ap_sig_allocacmp_state_1549_0_load_1;

assign ap_return_16 = ap_sig_allocacmp_state_16_0_load_1;

assign ap_return_17 = ap_sig_allocacmp_state_17_0_load_1;

assign ap_return_18 = ap_sig_allocacmp_state_18_0_load_1;

assign ap_return_19 = ap_sig_allocacmp_state_19_0_load_1;

assign ap_return_2 = ap_sig_allocacmp_state_2_0_load_1;

assign ap_return_20 = ap_sig_allocacmp_state_20_0_load_1;

assign ap_return_21 = ap_sig_allocacmp_state_21_0_load_1;

assign ap_return_22 = ap_sig_allocacmp_state_22_0_load_1;

assign ap_return_23 = ap_sig_allocacmp_state_2325_0_load_1;

assign ap_return_24 = ap_sig_allocacmp_state_24_0_load_1;

assign ap_return_3 = ap_sig_allocacmp_state_3_0_load_1;

assign ap_return_4 = ap_sig_allocacmp_state_4_0_load_1;

assign ap_return_5 = ap_sig_allocacmp_state_5_0_load_1;

assign ap_return_6 = ap_sig_allocacmp_state_6_0_load_1;

assign ap_return_7 = ap_sig_allocacmp_state_7_0_load_1;

assign ap_return_8 = ap_sig_allocacmp_state_8_0_load_1;

assign ap_return_9 = ap_sig_allocacmp_state_9_0_load_1;

assign icmp_ln157_fu_628_p2 = ((ap_sig_allocacmp_round_1 == 5'd24) ? 1'b1 : 1'b0);

assign lshr_ln22_10_fu_1369_p4 = {{x_16_fu_1119_p2[63:50]}};

assign lshr_ln22_11_fu_1391_p4 = {{x_17_fu_999_p2[63:37]}};

assign lshr_ln22_12_fu_1413_p4 = {{x_18_fu_1065_p2[63:23]}};

assign lshr_ln22_13_fu_1435_p4 = {{x_19_fu_1113_p2[63:8]}};

assign lshr_ln22_14_fu_1457_p4 = {{x_20_fu_1089_p2[63:56]}};

assign lshr_ln22_15_fu_1479_p4 = {{x_21_fu_1053_p2[63:39]}};

assign lshr_ln22_16_fu_1501_p4 = {{x_22_fu_1047_p2[63:21]}};

assign lshr_ln22_17_fu_1523_p4 = {{x_23_fu_987_p2[63:2]}};

assign lshr_ln22_18_fu_1545_p4 = {{x_24_fu_1095_p2[63:46]}};

assign lshr_ln22_19_fu_1567_p4 = {{x_25_fu_1059_p2[63:25]}};

assign lshr_ln22_1_fu_1259_p4 = {{x_11_fu_993_p2[63:36]}};

assign lshr_ln22_20_fu_1589_p4 = {{x_26_fu_1107_p2[63:3]}};

assign lshr_ln22_21_fu_1611_p4 = {{x_27_fu_1029_p2[63:44]}};

assign lshr_ln22_22_fu_1633_p4 = {{x_28_fu_1011_p2[63:20]}};

assign lshr_ln22_2_fu_1281_p4 = {{x_12_fu_1005_p2[63:28]}};

assign lshr_ln22_3_fu_1303_p4 = {{x_13_fu_1071_p2[63:19]}};

assign lshr_ln22_4_fu_1325_p4 = {{x_14_fu_1023_p2[63:9]}};

assign lshr_ln22_5_fu_1347_p4 = {{x_15_fu_1101_p2[63:62]}};

assign lshr_ln22_6_fu_1149_p4 = {{x_6_fu_1035_p2[63:61]}};

assign lshr_ln22_7_fu_1171_p4 = {{x_7_fu_1017_p2[63:58]}};

assign lshr_ln22_8_fu_1193_p4 = {{x_8_fu_1041_p2[63:54]}};

assign lshr_ln22_9_fu_1215_p4 = {{x_9_fu_1077_p2[63:49]}};

assign lshr_ln22_s_fu_1237_p4 = {{x_10_fu_1083_p2[63:43]}};

assign or_ln22_10_fu_1269_p3 = {{trunc_ln22_11_fu_1255_p1}, {lshr_ln22_1_fu_1259_p4}};

assign or_ln22_11_fu_1291_p3 = {{trunc_ln22_12_fu_1277_p1}, {lshr_ln22_2_fu_1281_p4}};

assign or_ln22_12_fu_1313_p3 = {{trunc_ln22_13_fu_1299_p1}, {lshr_ln22_3_fu_1303_p4}};

assign or_ln22_13_fu_1335_p3 = {{trunc_ln22_14_fu_1321_p1}, {lshr_ln22_4_fu_1325_p4}};

assign or_ln22_14_fu_1357_p3 = {{trunc_ln22_15_fu_1343_p1}, {lshr_ln22_5_fu_1347_p4}};

assign or_ln22_15_fu_1379_p3 = {{trunc_ln22_16_fu_1365_p1}, {lshr_ln22_10_fu_1369_p4}};

assign or_ln22_16_fu_1401_p3 = {{trunc_ln22_17_fu_1387_p1}, {lshr_ln22_11_fu_1391_p4}};

assign or_ln22_17_fu_1423_p3 = {{trunc_ln22_18_fu_1409_p1}, {lshr_ln22_12_fu_1413_p4}};

assign or_ln22_18_fu_1445_p3 = {{trunc_ln22_19_fu_1431_p1}, {lshr_ln22_13_fu_1435_p4}};

assign or_ln22_19_fu_1467_p3 = {{trunc_ln22_20_fu_1453_p1}, {lshr_ln22_14_fu_1457_p4}};

assign or_ln22_1_fu_883_p3 = {{trunc_ln22_1_fu_871_p1}, {tmp_16_fu_875_p3}};

assign or_ln22_20_fu_1489_p3 = {{trunc_ln22_21_fu_1475_p1}, {lshr_ln22_15_fu_1479_p4}};

assign or_ln22_21_fu_1511_p3 = {{trunc_ln22_22_fu_1497_p1}, {lshr_ln22_16_fu_1501_p4}};

assign or_ln22_22_fu_1533_p3 = {{trunc_ln22_23_fu_1519_p1}, {lshr_ln22_17_fu_1523_p4}};

assign or_ln22_23_fu_1555_p3 = {{trunc_ln22_24_fu_1541_p1}, {lshr_ln22_18_fu_1545_p4}};

assign or_ln22_24_fu_1577_p3 = {{trunc_ln22_25_fu_1563_p1}, {lshr_ln22_19_fu_1567_p4}};

assign or_ln22_25_fu_1599_p3 = {{trunc_ln22_26_fu_1585_p1}, {lshr_ln22_20_fu_1589_p4}};

assign or_ln22_26_fu_1621_p3 = {{trunc_ln22_27_fu_1607_p1}, {lshr_ln22_21_fu_1611_p4}};

assign or_ln22_27_fu_1643_p3 = {{trunc_ln22_28_fu_1629_p1}, {lshr_ln22_22_fu_1633_p4}};

assign or_ln22_2_fu_909_p3 = {{trunc_ln22_2_fu_897_p1}, {tmp_17_fu_901_p3}};

assign or_ln22_3_fu_935_p3 = {{trunc_ln22_3_fu_923_p1}, {tmp_18_fu_927_p3}};

assign or_ln22_4_fu_961_p3 = {{trunc_ln22_4_fu_949_p1}, {tmp_19_fu_953_p3}};

assign or_ln22_5_fu_1137_p3 = {{trunc_ln22_5_fu_1125_p1}, {tmp_20_fu_1129_p3}};

assign or_ln22_6_fu_1159_p3 = {{trunc_ln22_6_fu_1145_p1}, {lshr_ln22_6_fu_1149_p4}};

assign or_ln22_7_fu_1181_p3 = {{trunc_ln22_7_fu_1167_p1}, {lshr_ln22_7_fu_1171_p4}};

assign or_ln22_8_fu_1203_p3 = {{trunc_ln22_8_fu_1189_p1}, {lshr_ln22_8_fu_1193_p4}};

assign or_ln22_9_fu_1225_p3 = {{trunc_ln22_9_fu_1211_p1}, {lshr_ln22_9_fu_1215_p4}};

assign or_ln22_s_fu_1247_p3 = {{trunc_ln22_10_fu_1233_p1}, {lshr_ln22_s_fu_1237_p4}};

assign or_ln_fu_857_p3 = {{trunc_ln22_fu_845_p1}, {tmp_fu_849_p3}};

assign tmp_16_fu_875_p3 = x_1_fu_791_p2[32'd63];

assign tmp_17_fu_901_p3 = x_2_fu_815_p2[32'd63];

assign tmp_18_fu_927_p3 = x_3_fu_839_p2[32'd63];

assign tmp_19_fu_953_p3 = x_4_fu_743_p2[32'd63];

assign tmp_20_fu_1129_p3 = x_5_fu_981_p2[32'd63];

assign tmp_fu_849_p3 = x_fu_767_p2[32'd63];

assign trunc_ln22_10_fu_1233_p1 = x_10_fu_1083_p2[42:0];

assign trunc_ln22_11_fu_1255_p1 = x_11_fu_993_p2[35:0];

assign trunc_ln22_12_fu_1277_p1 = x_12_fu_1005_p2[27:0];

assign trunc_ln22_13_fu_1299_p1 = x_13_fu_1071_p2[18:0];

assign trunc_ln22_14_fu_1321_p1 = x_14_fu_1023_p2[8:0];

assign trunc_ln22_15_fu_1343_p1 = x_15_fu_1101_p2[61:0];

assign trunc_ln22_16_fu_1365_p1 = x_16_fu_1119_p2[49:0];

assign trunc_ln22_17_fu_1387_p1 = x_17_fu_999_p2[36:0];

assign trunc_ln22_18_fu_1409_p1 = x_18_fu_1065_p2[22:0];

assign trunc_ln22_19_fu_1431_p1 = x_19_fu_1113_p2[7:0];

assign trunc_ln22_1_fu_871_p1 = x_1_fu_791_p2[62:0];

assign trunc_ln22_20_fu_1453_p1 = x_20_fu_1089_p2[55:0];

assign trunc_ln22_21_fu_1475_p1 = x_21_fu_1053_p2[38:0];

assign trunc_ln22_22_fu_1497_p1 = x_22_fu_1047_p2[20:0];

assign trunc_ln22_23_fu_1519_p1 = x_23_fu_987_p2[1:0];

assign trunc_ln22_24_fu_1541_p1 = x_24_fu_1095_p2[45:0];

assign trunc_ln22_25_fu_1563_p1 = x_25_fu_1059_p2[24:0];

assign trunc_ln22_26_fu_1585_p1 = x_26_fu_1107_p2[2:0];

assign trunc_ln22_27_fu_1607_p1 = x_27_fu_1029_p2[43:0];

assign trunc_ln22_28_fu_1629_p1 = x_28_fu_1011_p2[19:0];

assign trunc_ln22_2_fu_897_p1 = x_2_fu_815_p2[62:0];

assign trunc_ln22_3_fu_923_p1 = x_3_fu_839_p2[62:0];

assign trunc_ln22_4_fu_949_p1 = x_4_fu_743_p2[62:0];

assign trunc_ln22_5_fu_1125_p1 = x_5_fu_981_p2[62:0];

assign trunc_ln22_6_fu_1145_p1 = x_6_fu_1035_p2[60:0];

assign trunc_ln22_7_fu_1167_p1 = x_7_fu_1017_p2[57:0];

assign trunc_ln22_8_fu_1189_p1 = x_8_fu_1041_p2[53:0];

assign trunc_ln22_9_fu_1211_p1 = x_9_fu_1077_p2[48:0];

assign trunc_ln22_fu_845_p1 = x_fu_767_p2[62:0];

assign x_10_fu_1083_p2 = (xor_ln57_3_fu_943_p2 ^ state_18_0_fu_300);

assign x_11_fu_993_p2 = (xor_ln57_3_fu_943_p2 ^ state_3_0_fu_228);

assign x_12_fu_1005_p2 = (xor_ln57_fu_865_p2 ^ state_5_0_fu_236);

assign x_13_fu_1071_p2 = (xor_ln57_1_fu_891_p2 ^ state_16_0_fu_264);

assign x_14_fu_1023_p2 = (xor_ln57_3_fu_943_p2 ^ state_8_0_fu_292);

assign x_15_fu_1101_p2 = (xor_ln57_1_fu_891_p2 ^ state_21_0_fu_268);

assign x_16_fu_1119_p2 = (xor_ln57_4_fu_969_p2 ^ state_24_0_fu_324);

assign x_17_fu_999_p2 = (xor_ln57_4_fu_969_p2 ^ state_4_0_fu_308);

assign x_18_fu_1065_p2 = (xor_ln57_fu_865_p2 ^ state_1549_0_fu_244);

assign x_19_fu_1113_p2 = (xor_ln57_3_fu_943_p2 ^ state_2325_0_fu_304);

assign x_1_fu_791_p2 = (xor_ln50_8_fu_773_p2 ^ xor_ln50_10_fu_785_p2);

assign x_20_fu_1089_p2 = (xor_ln57_4_fu_969_p2 ^ state_19_0_fu_320);

assign x_21_fu_1053_p2 = (xor_ln57_3_fu_943_p2 ^ state_13_0_fu_296);

assign x_22_fu_1047_p2 = (xor_ln57_2_fu_917_p2 ^ state_1213_0_fu_280);

assign x_23_fu_987_p2 = (xor_ln57_2_fu_917_p2 ^ state_2_0_fu_272);

assign x_24_fu_1095_p2 = (xor_ln57_fu_865_p2 ^ state_20_0_fu_248);

assign x_25_fu_1059_p2 = (xor_ln57_4_fu_969_p2 ^ state_14_0_fu_316);

assign x_26_fu_1107_p2 = (xor_ln57_2_fu_917_p2 ^ state_22_0_fu_288);

assign x_27_fu_1029_p2 = (xor_ln57_4_fu_969_p2 ^ state_9_0_fu_312);

assign x_28_fu_1011_p2 = (xor_ln57_1_fu_891_p2 ^ state_6_0_fu_256);

assign x_2_fu_815_p2 = (xor_ln50_14_fu_809_p2 ^ xor_ln50_12_fu_797_p2);

assign x_3_fu_839_p2 = (xor_ln50_18_fu_833_p2 ^ xor_ln50_16_fu_821_p2);

assign x_4_fu_743_p2 = (xor_ln50_fu_725_p2 ^ xor_ln50_2_fu_737_p2);

assign x_5_fu_981_p2 = (xor_ln57_1_fu_891_p2 ^ state_1_0_fu_252);

assign x_6_fu_1035_p2 = (xor_ln57_fu_865_p2 ^ state_10_0_fu_240);

assign x_7_fu_1017_p2 = (xor_ln57_2_fu_917_p2 ^ state_7_0_fu_276);

assign x_8_fu_1041_p2 = (xor_ln57_1_fu_891_p2 ^ state_11_0_fu_260);

assign x_9_fu_1077_p2 = (xor_ln57_2_fu_917_p2 ^ state_17_0_fu_284);

assign x_fu_767_p2 = (xor_ln50_6_fu_761_p2 ^ xor_ln50_4_fu_749_p2);

assign xor_ln135_10_fu_1741_p2 = (or_ln22_6_fu_1159_p3 ^ 64'd18446744073709551615);

assign xor_ln135_11_fu_1753_p2 = (or_ln22_26_fu_1621_p3 ^ and_ln135_5_fu_1747_p2);

assign xor_ln135_12_fu_1759_p2 = (or_ln22_12_fu_1313_p3 ^ 64'd18446744073709551615);

assign xor_ln135_13_fu_1771_p2 = (or_ln22_6_fu_1159_p3 ^ and_ln135_6_fu_1765_p2);

assign xor_ln135_14_fu_1777_p2 = (or_ln22_25_fu_1599_p3 ^ 64'd18446744073709551615);

assign xor_ln135_15_fu_1789_p2 = (or_ln22_12_fu_1313_p3 ^ and_ln135_7_fu_1783_p2);

assign xor_ln135_16_fu_1795_p2 = (or_ln22_10_fu_1269_p3 ^ 64'd18446744073709551615);

assign xor_ln135_17_fu_1807_p2 = (or_ln22_25_fu_1599_p3 ^ and_ln135_8_fu_1801_p2);

assign xor_ln135_18_fu_1813_p2 = (or_ln22_7_fu_1181_p3 ^ 64'd18446744073709551615);

assign xor_ln135_19_fu_1825_p2 = (or_ln22_5_fu_1137_p3 ^ and_ln135_9_fu_1819_p2);

assign xor_ln135_1_fu_1663_p2 = (or_ln22_27_fu_1643_p3 ^ and_ln135_fu_1657_p2);

assign xor_ln135_20_fu_1831_p2 = (or_ln22_20_fu_1489_p3 ^ 64'd18446744073709551615);

assign xor_ln135_21_fu_1843_p2 = (or_ln22_7_fu_1181_p3 ^ and_ln135_10_fu_1837_p2);

assign xor_ln135_22_fu_1849_p2 = (or_ln22_19_fu_1467_p3 ^ 64'd18446744073709551615);

assign xor_ln135_23_fu_1861_p2 = (or_ln22_20_fu_1489_p3 ^ and_ln135_11_fu_1855_p2);

assign xor_ln135_24_fu_1867_p2 = (or_ln22_23_fu_1555_p3 ^ 64'd18446744073709551615);

assign xor_ln135_25_fu_1879_p2 = (or_ln22_19_fu_1467_p3 ^ and_ln135_12_fu_1873_p2);

assign xor_ln135_26_fu_1885_p2 = (or_ln22_5_fu_1137_p3 ^ 64'd18446744073709551615);

assign xor_ln135_27_fu_1897_p2 = (or_ln22_23_fu_1555_p3 ^ and_ln135_13_fu_1891_p2);

assign xor_ln135_28_fu_1903_p2 = (or_ln22_11_fu_1291_p3 ^ 64'd18446744073709551615);

assign xor_ln135_29_fu_1915_p2 = (or_ln22_16_fu_1401_p3 ^ and_ln135_14_fu_1909_p2);

assign xor_ln135_2_fu_1669_p2 = (or_ln22_s_fu_1247_p3 ^ 64'd18446744073709551615);

assign xor_ln135_30_fu_1921_p2 = (or_ln22_8_fu_1203_p3 ^ 64'd18446744073709551615);

assign xor_ln135_31_fu_1933_p2 = (or_ln22_11_fu_1291_p3 ^ and_ln135_15_fu_1927_p2);

assign xor_ln135_32_fu_1939_p2 = (or_ln22_9_fu_1225_p3 ^ 64'd18446744073709551615);

assign xor_ln135_33_fu_1951_p2 = (or_ln22_8_fu_1203_p3 ^ and_ln135_16_fu_1945_p2);

assign xor_ln135_34_fu_1957_p2 = (or_ln22_18_fu_1445_p3 ^ 64'd18446744073709551615);

assign xor_ln135_35_fu_1969_p2 = (or_ln22_9_fu_1225_p3 ^ and_ln135_17_fu_1963_p2);

assign xor_ln135_36_fu_1975_p2 = (or_ln22_16_fu_1401_p3 ^ 64'd18446744073709551615);

assign xor_ln135_37_fu_1987_p2 = (or_ln22_18_fu_1445_p3 ^ and_ln135_18_fu_1981_p2);

assign xor_ln135_38_fu_1993_p2 = (or_ln22_13_fu_1335_p3 ^ 64'd18446744073709551615);

assign xor_ln135_39_fu_2005_p2 = (or_ln22_22_fu_1533_p3 ^ and_ln135_19_fu_1999_p2);

assign xor_ln135_3_fu_1681_p2 = (or_ln22_21_fu_1511_p3 ^ and_ln135_1_fu_1675_p2);

assign xor_ln135_40_fu_2011_p2 = (or_ln22_24_fu_1577_p3 ^ 64'd18446744073709551615);

assign xor_ln135_41_fu_2023_p2 = (or_ln22_13_fu_1335_p3 ^ and_ln135_20_fu_2017_p2);

assign xor_ln135_42_fu_2029_p2 = (or_ln22_17_fu_1423_p3 ^ 64'd18446744073709551615);

assign xor_ln135_43_fu_2041_p2 = (or_ln22_24_fu_1577_p3 ^ and_ln135_21_fu_2035_p2);

assign xor_ln135_44_fu_2047_p2 = (or_ln22_14_fu_1357_p3 ^ 64'd18446744073709551615);

assign xor_ln135_45_fu_2059_p2 = (or_ln22_17_fu_1423_p3 ^ and_ln135_22_fu_2053_p2);

assign xor_ln135_46_fu_2065_p2 = (or_ln22_22_fu_1533_p3 ^ 64'd18446744073709551615);

assign xor_ln135_47_fu_2077_p2 = (or_ln22_14_fu_1357_p3 ^ and_ln135_23_fu_2071_p2);

assign xor_ln135_4_fu_1687_p2 = (or_ln22_15_fu_1379_p3 ^ 64'd18446744073709551615);

assign xor_ln135_5_fu_1699_p2 = (or_ln22_s_fu_1247_p3 ^ and_ln135_2_fu_1693_p2);

assign xor_ln135_6_fu_1705_p2 = (xor_ln67_fu_975_p2 ^ 64'd18446744073709551615);

assign xor_ln135_7_fu_1717_p2 = (or_ln22_15_fu_1379_p3 ^ and_ln135_3_fu_1711_p2);

assign xor_ln135_8_fu_1723_p2 = (or_ln22_26_fu_1621_p3 ^ 64'd18446744073709551615);

assign xor_ln135_9_fu_1735_p2 = (or_ln22_10_fu_1269_p3 ^ and_ln135_4_fu_1729_p2);

assign xor_ln135_fu_1651_p2 = (or_ln22_21_fu_1511_p3 ^ 64'd18446744073709551615);

assign xor_ln145_1_fu_2095_p2 = (xor_ln67_fu_975_p2 ^ and_ln145_fu_2089_p2);

assign xor_ln145_2_fu_2101_p2 = (xor_ln145_1_fu_2095_p2 ^ RC_TABLE_q0);

assign xor_ln145_fu_2083_p2 = (or_ln22_27_fu_1643_p3 ^ 64'd18446744073709551615);

assign xor_ln50_10_fu_785_p2 = (xor_ln50_9_fu_779_p2 ^ state_22_0_fu_288);

assign xor_ln50_12_fu_797_p2 = (state_8_0_fu_292 ^ state_13_0_fu_296);

assign xor_ln50_13_fu_803_p2 = (state_3_0_fu_228 ^ state_18_0_fu_300);

assign xor_ln50_14_fu_809_p2 = (xor_ln50_13_fu_803_p2 ^ state_2325_0_fu_304);

assign xor_ln50_16_fu_821_p2 = (state_9_0_fu_312 ^ state_14_0_fu_316);

assign xor_ln50_17_fu_827_p2 = (state_4_0_fu_308 ^ state_19_0_fu_320);

assign xor_ln50_18_fu_833_p2 = (xor_ln50_17_fu_827_p2 ^ state_24_0_fu_324);

assign xor_ln50_1_fu_731_p2 = (state_1549_0_fu_244 ^ state_0_0_fu_232);

assign xor_ln50_2_fu_737_p2 = (xor_ln50_1_fu_731_p2 ^ state_20_0_fu_248);

assign xor_ln50_4_fu_749_p2 = (state_6_0_fu_256 ^ state_11_0_fu_260);

assign xor_ln50_5_fu_755_p2 = (state_1_0_fu_252 ^ state_16_0_fu_264);

assign xor_ln50_6_fu_761_p2 = (xor_ln50_5_fu_755_p2 ^ state_21_0_fu_268);

assign xor_ln50_8_fu_773_p2 = (state_7_0_fu_276 ^ state_1213_0_fu_280);

assign xor_ln50_9_fu_779_p2 = (state_2_0_fu_272 ^ state_17_0_fu_284);

assign xor_ln50_fu_725_p2 = (state_5_0_fu_236 ^ state_10_0_fu_240);

assign xor_ln57_1_fu_891_p2 = (x_4_fu_743_p2 ^ or_ln22_1_fu_883_p3);

assign xor_ln57_2_fu_917_p2 = (x_fu_767_p2 ^ or_ln22_2_fu_909_p3);

assign xor_ln57_3_fu_943_p2 = (x_1_fu_791_p2 ^ or_ln22_3_fu_935_p3);

assign xor_ln57_4_fu_969_p2 = (x_2_fu_815_p2 ^ or_ln22_4_fu_961_p3);

assign xor_ln57_fu_865_p2 = (x_3_fu_839_p2 ^ or_ln_fu_857_p3);

assign xor_ln67_fu_975_p2 = (xor_ln57_fu_865_p2 ^ state_0_0_fu_232);

assign zext_ln157_fu_640_p1 = ap_sig_allocacmp_round_1;

endmodule //keccak_top_keccak_f1600
